//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

//
// This source code was auto-generated by cf-sdk-builder
//

using CloudFoundry.CloudController.V2.Client;
using CloudFoundry.CloudController.V2.Client.Data;
using Microsoft.CSharp;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Newtonsoft.Json;
using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;

namespace CloudFoundry.CloudController.V2.Test.Serialization
{
    [TestClass]
    [GeneratedCodeAttribute("cf-sdk-builder", "1.0.0.0")]
    public class RoutesTest
    {

        [TestMethod]
        public void TestUpdateRouteRequest()
        {
            string json = @"{
  ""host"": ""new_host"",
  ""path"": ""/apps/v1/path""
}";

            UpdateRouteRequest request = new UpdateRouteRequest();

            request.Host = "new_host";
            request.Path = "/apps/v1/path";
            string result = JsonConvert.SerializeObject(request, Formatting.None);
            Assert.AreEqual(TestUtil.ToUnformatedJsonString(json), result);
        }
        [TestMethod]
        public void TestCreateRouteRequest()
        {
            string json = @"{
  ""domain_guid"": ""14e7c4a5-1b21-4d4b-ac7a-431f622f2fde"",
  ""space_guid"": ""b9039181-b780-422e-8a6c-9dad1fd6b9d3"",
  ""path"": ""/apps/v1/path""
}";

            CreateRouteRequest request = new CreateRouteRequest();

            request.DomainGuid = new Guid("14e7c4a5-1b21-4d4b-ac7a-431f622f2fde");
            request.SpaceGuid = new Guid("b9039181-b780-422e-8a6c-9dad1fd6b9d3");
            request.Path = "/apps/v1/path";
            string result = JsonConvert.SerializeObject(request, Formatting.None);
            Assert.AreEqual(TestUtil.ToUnformatedJsonString(json), result);
        }
    }
}
