//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

//
// This source code was auto-generated by cf-sdk-builder
//

using CloudFoundry.CloudController.V2.Client;
using CloudFoundry.CloudController.V2.Client.Data;
using Microsoft.CSharp;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Newtonsoft.Json;
using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;

namespace CloudFoundry.CloudController.V2.Test.Serialization
{
    [TestClass]
    [GeneratedCodeAttribute("cf-sdk-builder", "1.0.0.0")]
    public class ServicePlansTest
    {

        [TestMethod]
        public void TestUpdateServicePlanDeprecatedRequest()
        {
            string json = @"{
  ""name"": ""100mb"",
  ""free"": true,
  ""description"": ""Let's you put data in your database!"",
  ""service_guid"": ""536bf8a8-d818-4034-b18f-930f27321f06""
}";

            UpdateServicePlanDeprecatedRequest request = new UpdateServicePlanDeprecatedRequest();

            request.Name = "100mb";
            request.Free = true;
            request.Description = "Let's you put data in your database!";
            request.ServiceGuid = new Guid("536bf8a8-d818-4034-b18f-930f27321f06");
            string result = JsonConvert.SerializeObject(request, Formatting.None);
            Assert.AreEqual(TestUtil.ToUnformatedJsonString(json), result);
        }
        [TestMethod]
        public void TestCreateServicePlanDeprecatedRequest()
        {
            string json = @"{
  ""name"": ""100mb"",
  ""free"": true,
  ""description"": ""Let's you put data in your database!"",
  ""service_guid"": ""741fcbe4-ede2-49fb-8593-a1c6374e316d""
}";

            CreateServicePlanDeprecatedRequest request = new CreateServicePlanDeprecatedRequest();

            request.Name = "100mb";
            request.Free = true;
            request.Description = "Let's you put data in your database!";
            request.ServiceGuid = new Guid("741fcbe4-ede2-49fb-8593-a1c6374e316d");
            string result = JsonConvert.SerializeObject(request, Formatting.None);
            Assert.AreEqual(TestUtil.ToUnformatedJsonString(json), result);
        }
    }
}
