//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

//
// This source code was auto-generated by cf-sdk-builder
//

using CloudFoundry.CloudController.V2.Client;
using CloudFoundry.CloudController.V2.Client.Data;
using Microsoft.CSharp;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using Newtonsoft.Json;
using System;
using System.CodeDom.Compiler;
using System.Collections.Generic;

namespace CloudFoundry.CloudController.V2.Test.Serialization
{
    [TestClass]
    [GeneratedCodeAttribute("cf-sdk-builder", "1.0.0.0")]
    public class ServiceBindingsTest
    {

        [TestMethod]
        public void TestCreateServiceBindingRequest()
        {
            string json = @"{
  ""service_instance_guid"": ""bb6db52a-149a-4dea-ba65-61359718c428"",
  ""app_guid"": ""69878955-e42e-4822-b4e0-13c5d2a91a29"",
  ""parameters"": {
    ""the_service_broker"": ""wants this object""
  }
}";

            CreateServiceBindingRequest request = new CreateServiceBindingRequest();

            request.ServiceInstanceGuid = new Guid("bb6db52a-149a-4dea-ba65-61359718c428");
            request.AppGuid = new Guid("69878955-e42e-4822-b4e0-13c5d2a91a29");
            request.Parameters = TestUtil.GetJsonDictonary(@"{""the_service_broker"":""wants this object""}");

            string result = JsonConvert.SerializeObject(request, Formatting.None);
            Assert.AreEqual(TestUtil.ToUnformatedJsonString(json), result);
        }
    }
}
