//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

//
// This source code was auto-generated by cf-sdk-builder
//

using CloudFoundry.CloudController.V2.Client;
using CloudFoundry.CloudController.V2.Client.Data;
using Microsoft.CSharp;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System.CodeDom.Compiler;

namespace CloudFoundry.CloudController.V2.Test.Deserialization
{
    [TestClass]
    [GeneratedCodeAttribute("cf-sdk-builder", "1.0.0.0")]
    public class ServiceBindingsTest
    {


        [TestMethod]
        public void TestRetrieveServiceBindingResponse()
        {
            string json = @"{
  ""metadata"": {
    ""guid"": ""eaad3a28-6501-4b4d-8b43-74eba86feabc"",
    ""url"": ""/v2/service_bindings/eaad3a28-6501-4b4d-8b43-74eba86feabc"",
    ""created_at"": ""2015-07-29T12:47:14Z"",
    ""updated_at"": null
  },
  ""entity"": {
    ""app_guid"": ""4779a135-3f95-495f-b7f6-57ae5ebfa0db"",
    ""service_instance_guid"": ""183e8cf7-2e1e-4438-a2c5-512c4c746410"",
    ""credentials"": {
      ""creds-key-12"": ""creds-val-12""
    },
    ""binding_options"": {

    },
    ""gateway_data"": null,
    ""gateway_name"": """",
    ""syslog_drain_url"": null,
    ""app_url"": ""/v2/apps/4779a135-3f95-495f-b7f6-57ae5ebfa0db"",
    ""service_instance_url"": ""/v2/service_instances/183e8cf7-2e1e-4438-a2c5-512c4c746410""
  }
}";

            RetrieveServiceBindingResponse obj = Utilities.DeserializeJson<RetrieveServiceBindingResponse>(json);

            Assert.AreEqual("eaad3a28-6501-4b4d-8b43-74eba86feabc", TestUtil.ToTestableString(obj.EntityMetadata.Guid), true);
            Assert.AreEqual("/v2/service_bindings/eaad3a28-6501-4b4d-8b43-74eba86feabc", TestUtil.ToTestableString(obj.EntityMetadata.Url), true);
            Assert.AreEqual("2015-07-29T12:47:14Z", TestUtil.ToTestableString(obj.EntityMetadata.CreatedAt), true);
            Assert.AreEqual("", TestUtil.ToTestableString(obj.EntityMetadata.UpdatedAt), true);
            Assert.AreEqual("4779a135-3f95-495f-b7f6-57ae5ebfa0db", TestUtil.ToTestableString(obj.AppGuid), true);
            Assert.AreEqual("183e8cf7-2e1e-4438-a2c5-512c4c746410", TestUtil.ToTestableString(obj.ServiceInstanceGuid), true);
            Assert.AreEqual("", TestUtil.ToTestableString(obj.GatewayData), true);
            Assert.AreEqual("", TestUtil.ToTestableString(obj.GatewayName), true);
            Assert.AreEqual("", TestUtil.ToTestableString(obj.SyslogDrainUrl), true);
            Assert.AreEqual("/v2/apps/4779a135-3f95-495f-b7f6-57ae5ebfa0db", TestUtil.ToTestableString(obj.AppUrl), true);
            Assert.AreEqual("/v2/service_instances/183e8cf7-2e1e-4438-a2c5-512c4c746410", TestUtil.ToTestableString(obj.ServiceInstanceUrl), true);
        }

        [TestMethod]
        public void TestListAllServiceBindingsResponse()
        {
            string json = @"{
  ""total_results"": 1,
  ""total_pages"": 1,
  ""prev_url"": null,
  ""next_url"": null,
  ""resources"": [
    {
      ""metadata"": {
        ""guid"": ""7bc9b5d1-bd71-4a12-a950-4964f4a3bcfd"",
        ""url"": ""/v2/service_bindings/7bc9b5d1-bd71-4a12-a950-4964f4a3bcfd"",
        ""created_at"": ""2015-07-29T12:47:14Z"",
        ""updated_at"": null
      },
      ""entity"": {
        ""app_guid"": ""23cba94e-2ba1-4991-b3c8-329c44b5cd81"",
        ""service_instance_guid"": ""67c7ef44-9ee6-4c80-bf2f-435f8f21b5e3"",
        ""credentials"": {
          ""creds-key-16"": ""creds-val-16""
        },
        ""binding_options"": {

        },
        ""gateway_data"": null,
        ""gateway_name"": """",
        ""syslog_drain_url"": null,
        ""app_url"": ""/v2/apps/23cba94e-2ba1-4991-b3c8-329c44b5cd81"",
        ""service_instance_url"": ""/v2/service_instances/67c7ef44-9ee6-4c80-bf2f-435f8f21b5e3""
      }
    }
  ]
}";

            PagedResponseCollection<ListAllServiceBindingsResponse> page = Utilities.DeserializePage<ListAllServiceBindingsResponse>(json, null);

            Assert.AreEqual("1", TestUtil.ToTestableString(page.Properties.TotalResults), true);
            Assert.AreEqual("1", TestUtil.ToTestableString(page.Properties.TotalPages), true);
            Assert.AreEqual("", TestUtil.ToTestableString(page.Properties.PreviousUrl), true);
            Assert.AreEqual("", TestUtil.ToTestableString(page.Properties.NextUrl), true);
            Assert.AreEqual("7bc9b5d1-bd71-4a12-a950-4964f4a3bcfd", TestUtil.ToTestableString(page[0].EntityMetadata.Guid), true);
            Assert.AreEqual("/v2/service_bindings/7bc9b5d1-bd71-4a12-a950-4964f4a3bcfd", TestUtil.ToTestableString(page[0].EntityMetadata.Url), true);
            Assert.AreEqual("2015-07-29T12:47:14Z", TestUtil.ToTestableString(page[0].EntityMetadata.CreatedAt), true);
            Assert.AreEqual("", TestUtil.ToTestableString(page[0].EntityMetadata.UpdatedAt), true);
            Assert.AreEqual("23cba94e-2ba1-4991-b3c8-329c44b5cd81", TestUtil.ToTestableString(page[0].AppGuid), true);
            Assert.AreEqual("67c7ef44-9ee6-4c80-bf2f-435f8f21b5e3", TestUtil.ToTestableString(page[0].ServiceInstanceGuid), true);
            Assert.AreEqual("", TestUtil.ToTestableString(page[0].GatewayData), true);
            Assert.AreEqual("", TestUtil.ToTestableString(page[0].GatewayName), true);
            Assert.AreEqual("", TestUtil.ToTestableString(page[0].SyslogDrainUrl), true);
            Assert.AreEqual("/v2/apps/23cba94e-2ba1-4991-b3c8-329c44b5cd81", TestUtil.ToTestableString(page[0].AppUrl), true);
            Assert.AreEqual("/v2/service_instances/67c7ef44-9ee6-4c80-bf2f-435f8f21b5e3", TestUtil.ToTestableString(page[0].ServiceInstanceUrl), true);
        }

        [TestMethod]
        public void TestCreateServiceBindingResponse()
        {
            string json = @"{
  ""metadata"": {
    ""guid"": ""9e48f66b-6cde-4b32-99f5-5c8bf780d5cf"",
    ""url"": ""/v2/service_bindings/9e48f66b-6cde-4b32-99f5-5c8bf780d5cf"",
    ""created_at"": ""2015-07-29T12:47:13Z"",
    ""updated_at"": null
  },
  ""entity"": {
    ""app_guid"": ""69878955-e42e-4822-b4e0-13c5d2a91a29"",
    ""service_instance_guid"": ""bb6db52a-149a-4dea-ba65-61359718c428"",
    ""credentials"": {
      ""creds-key-5"": ""creds-val-5""
    },
    ""binding_options"": {

    },
    ""gateway_data"": null,
    ""gateway_name"": """",
    ""syslog_drain_url"": null,
    ""app_url"": ""/v2/apps/69878955-e42e-4822-b4e0-13c5d2a91a29"",
    ""service_instance_url"": ""/v2/user_provided_service_instances/bb6db52a-149a-4dea-ba65-61359718c428""
  }
}";

            CreateServiceBindingResponse obj = Utilities.DeserializeJson<CreateServiceBindingResponse>(json);

            Assert.AreEqual("9e48f66b-6cde-4b32-99f5-5c8bf780d5cf", TestUtil.ToTestableString(obj.EntityMetadata.Guid), true);
            Assert.AreEqual("/v2/service_bindings/9e48f66b-6cde-4b32-99f5-5c8bf780d5cf", TestUtil.ToTestableString(obj.EntityMetadata.Url), true);
            Assert.AreEqual("2015-07-29T12:47:13Z", TestUtil.ToTestableString(obj.EntityMetadata.CreatedAt), true);
            Assert.AreEqual("", TestUtil.ToTestableString(obj.EntityMetadata.UpdatedAt), true);
            Assert.AreEqual("69878955-e42e-4822-b4e0-13c5d2a91a29", TestUtil.ToTestableString(obj.AppGuid), true);
            Assert.AreEqual("bb6db52a-149a-4dea-ba65-61359718c428", TestUtil.ToTestableString(obj.ServiceInstanceGuid), true);
            Assert.AreEqual("", TestUtil.ToTestableString(obj.GatewayData), true);
            Assert.AreEqual("", TestUtil.ToTestableString(obj.GatewayName), true);
            Assert.AreEqual("", TestUtil.ToTestableString(obj.SyslogDrainUrl), true);
            Assert.AreEqual("/v2/apps/69878955-e42e-4822-b4e0-13c5d2a91a29", TestUtil.ToTestableString(obj.AppUrl), true);
            Assert.AreEqual("/v2/user_provided_service_instances/bb6db52a-149a-4dea-ba65-61359718c428", TestUtil.ToTestableString(obj.ServiceInstanceUrl), true);
        }
    }
}
