//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

//
// This source code was auto-generated by cf-sdk-builder
//

using CloudFoundry.CloudController.V2.Client;
using CloudFoundry.CloudController.V2.Client.Data;
using Microsoft.CSharp;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System.CodeDom.Compiler;

namespace CloudFoundry.CloudController.V2.Test.Deserialization
{
    [TestClass]
    [GeneratedCodeAttribute("cf-sdk-builder", "1.0.0.0")]
    public class SecurityGroupsTest
    {


        [TestMethod]
        public void TestUpdateSecurityGroupResponse()
        {
            string json = @"{
  ""metadata"": {
    ""guid"": ""bc3aa061-025a-45f6-8674-6a69944c42a9"",
    ""url"": ""/v2/security_groups/bc3aa061-025a-45f6-8674-6a69944c42a9"",
    ""created_at"": ""2016-02-05T12:14:47Z"",
    ""updated_at"": ""2016-02-05T12:14:49Z""
  },
  ""entity"": {
    ""name"": ""new_name"",
    ""rules"": [

    ],
    ""running_default"": false,
    ""staging_default"": false,
    ""spaces_url"": ""/v2/security_groups/bc3aa061-025a-45f6-8674-6a69944c42a9/spaces""
  }
}";

            UpdateSecurityGroupResponse obj = Utilities.DeserializeJson<UpdateSecurityGroupResponse>(json);

            Assert.AreEqual("bc3aa061-025a-45f6-8674-6a69944c42a9", TestUtil.ToTestableString(obj.EntityMetadata.Guid), true);
            Assert.AreEqual("/v2/security_groups/bc3aa061-025a-45f6-8674-6a69944c42a9", TestUtil.ToTestableString(obj.EntityMetadata.Url), true);
            Assert.AreEqual("2016-02-05T12:14:47Z", TestUtil.ToTestableString(obj.EntityMetadata.CreatedAt), true);
            Assert.AreEqual("2016-02-05T12:14:49Z", TestUtil.ToTestableString(obj.EntityMetadata.UpdatedAt), true);
            Assert.AreEqual("new_name", TestUtil.ToTestableString(obj.Name), true);
            Assert.AreEqual("false", TestUtil.ToTestableString(obj.RunningDefault), true);
            Assert.AreEqual("false", TestUtil.ToTestableString(obj.StagingDefault), true);
            Assert.AreEqual("/v2/security_groups/bc3aa061-025a-45f6-8674-6a69944c42a9/spaces", TestUtil.ToTestableString(obj.SpacesUrl), true);
        }

        [TestMethod]
        public void TestListAllSecurityGroupsResponse()
        {
            string json = @"{
  ""total_results"": 5,
  ""total_pages"": 1,
  ""prev_url"": null,
  ""next_url"": null,
  ""resources"": [
    {
      ""metadata"": {
        ""guid"": ""bc3aa061-025a-45f6-8674-6a69944c42a9"",
        ""url"": ""/v2/security_groups/bc3aa061-025a-45f6-8674-6a69944c42a9"",
        ""created_at"": ""2016-02-05T12:14:47Z"",
        ""updated_at"": null
      },
      ""entity"": {
        ""name"": ""dummy1"",
        ""rules"": [

        ],
        ""running_default"": false,
        ""staging_default"": false,
        ""spaces_url"": ""/v2/security_groups/bc3aa061-025a-45f6-8674-6a69944c42a9/spaces""
      }
    },
    {
      ""metadata"": {
        ""guid"": ""d038efe1-6c53-4495-b6ae-eb429144b342"",
        ""url"": ""/v2/security_groups/d038efe1-6c53-4495-b6ae-eb429144b342"",
        ""created_at"": ""2016-02-05T12:14:47Z"",
        ""updated_at"": null
      },
      ""entity"": {
        ""name"": ""dummy2"",
        ""rules"": [

        ],
        ""running_default"": false,
        ""staging_default"": false,
        ""spaces_url"": ""/v2/security_groups/d038efe1-6c53-4495-b6ae-eb429144b342/spaces""
      }
    },
    {
      ""metadata"": {
        ""guid"": ""bbd2435b-b536-4ff0-b83a-216e2d1f9051"",
        ""url"": ""/v2/security_groups/bbd2435b-b536-4ff0-b83a-216e2d1f9051"",
        ""created_at"": ""2016-02-05T12:14:49Z"",
        ""updated_at"": null
      },
      ""entity"": {
        ""name"": ""name-1818"",
        ""rules"": [
          {
            ""protocol"": ""udp"",
            ""ports"": ""8080"",
            ""destination"": ""198.41.191.47/1""
          }
        ],
        ""running_default"": false,
        ""staging_default"": false,
        ""spaces_url"": ""/v2/security_groups/bbd2435b-b536-4ff0-b83a-216e2d1f9051/spaces""
      }
    },
    {
      ""metadata"": {
        ""guid"": ""40512380-db93-4e89-85a3-64501ce8a802"",
        ""url"": ""/v2/security_groups/40512380-db93-4e89-85a3-64501ce8a802"",
        ""created_at"": ""2016-02-05T12:14:49Z"",
        ""updated_at"": null
      },
      ""entity"": {
        ""name"": ""name-1819"",
        ""rules"": [
          {
            ""protocol"": ""udp"",
            ""ports"": ""8080"",
            ""destination"": ""198.41.191.47/1""
          }
        ],
        ""running_default"": false,
        ""staging_default"": false,
        ""spaces_url"": ""/v2/security_groups/40512380-db93-4e89-85a3-64501ce8a802/spaces""
      }
    },
    {
      ""metadata"": {
        ""guid"": ""5e1c030b-fde8-4a91-a20c-cc8b4aedf470"",
        ""url"": ""/v2/security_groups/5e1c030b-fde8-4a91-a20c-cc8b4aedf470"",
        ""created_at"": ""2016-02-05T12:14:49Z"",
        ""updated_at"": null
      },
      ""entity"": {
        ""name"": ""name-1820"",
        ""rules"": [
          {
            ""protocol"": ""udp"",
            ""ports"": ""8080"",
            ""destination"": ""198.41.191.47/1""
          }
        ],
        ""running_default"": false,
        ""staging_default"": false,
        ""spaces_url"": ""/v2/security_groups/5e1c030b-fde8-4a91-a20c-cc8b4aedf470/spaces""
      }
    }
  ]
}";

            PagedResponseCollection<ListAllSecurityGroupsResponse> page = Utilities.DeserializePage<ListAllSecurityGroupsResponse>(json, null);

            Assert.AreEqual("5", TestUtil.ToTestableString(page.Properties.TotalResults), true);
            Assert.AreEqual("1", TestUtil.ToTestableString(page.Properties.TotalPages), true);
            Assert.AreEqual("", TestUtil.ToTestableString(page.Properties.PreviousUrl), true);
            Assert.AreEqual("", TestUtil.ToTestableString(page.Properties.NextUrl), true);
            Assert.AreEqual("bc3aa061-025a-45f6-8674-6a69944c42a9", TestUtil.ToTestableString(page[0].EntityMetadata.Guid), true);
            Assert.AreEqual("/v2/security_groups/bc3aa061-025a-45f6-8674-6a69944c42a9", TestUtil.ToTestableString(page[0].EntityMetadata.Url), true);
            Assert.AreEqual("2016-02-05T12:14:47Z", TestUtil.ToTestableString(page[0].EntityMetadata.CreatedAt), true);
            Assert.AreEqual("", TestUtil.ToTestableString(page[0].EntityMetadata.UpdatedAt), true);
            Assert.AreEqual("dummy1", TestUtil.ToTestableString(page[0].Name), true);
            Assert.AreEqual("false", TestUtil.ToTestableString(page[0].RunningDefault), true);
            Assert.AreEqual("false", TestUtil.ToTestableString(page[0].StagingDefault), true);
            Assert.AreEqual("/v2/security_groups/bc3aa061-025a-45f6-8674-6a69944c42a9/spaces", TestUtil.ToTestableString(page[0].SpacesUrl), true);
            Assert.AreEqual("d038efe1-6c53-4495-b6ae-eb429144b342", TestUtil.ToTestableString(page[1].EntityMetadata.Guid), true);
            Assert.AreEqual("/v2/security_groups/d038efe1-6c53-4495-b6ae-eb429144b342", TestUtil.ToTestableString(page[1].EntityMetadata.Url), true);
            Assert.AreEqual("2016-02-05T12:14:47Z", TestUtil.ToTestableString(page[1].EntityMetadata.CreatedAt), true);
            Assert.AreEqual("", TestUtil.ToTestableString(page[1].EntityMetadata.UpdatedAt), true);
            Assert.AreEqual("dummy2", TestUtil.ToTestableString(page[1].Name), true);
            Assert.AreEqual("false", TestUtil.ToTestableString(page[1].RunningDefault), true);
            Assert.AreEqual("false", TestUtil.ToTestableString(page[1].StagingDefault), true);
            Assert.AreEqual("/v2/security_groups/d038efe1-6c53-4495-b6ae-eb429144b342/spaces", TestUtil.ToTestableString(page[1].SpacesUrl), true);
            Assert.AreEqual("bbd2435b-b536-4ff0-b83a-216e2d1f9051", TestUtil.ToTestableString(page[2].EntityMetadata.Guid), true);
            Assert.AreEqual("/v2/security_groups/bbd2435b-b536-4ff0-b83a-216e2d1f9051", TestUtil.ToTestableString(page[2].EntityMetadata.Url), true);
            Assert.AreEqual("2016-02-05T12:14:49Z", TestUtil.ToTestableString(page[2].EntityMetadata.CreatedAt), true);
            Assert.AreEqual("", TestUtil.ToTestableString(page[2].EntityMetadata.UpdatedAt), true);
            Assert.AreEqual("name-1818", TestUtil.ToTestableString(page[2].Name), true);
            Assert.AreEqual("false", TestUtil.ToTestableString(page[2].RunningDefault), true);
            Assert.AreEqual("false", TestUtil.ToTestableString(page[2].StagingDefault), true);
            Assert.AreEqual("/v2/security_groups/bbd2435b-b536-4ff0-b83a-216e2d1f9051/spaces", TestUtil.ToTestableString(page[2].SpacesUrl), true);
            Assert.AreEqual("40512380-db93-4e89-85a3-64501ce8a802", TestUtil.ToTestableString(page[3].EntityMetadata.Guid), true);
            Assert.AreEqual("/v2/security_groups/40512380-db93-4e89-85a3-64501ce8a802", TestUtil.ToTestableString(page[3].EntityMetadata.Url), true);
            Assert.AreEqual("2016-02-05T12:14:49Z", TestUtil.ToTestableString(page[3].EntityMetadata.CreatedAt), true);
            Assert.AreEqual("", TestUtil.ToTestableString(page[3].EntityMetadata.UpdatedAt), true);
            Assert.AreEqual("name-1819", TestUtil.ToTestableString(page[3].Name), true);
            Assert.AreEqual("false", TestUtil.ToTestableString(page[3].RunningDefault), true);
            Assert.AreEqual("false", TestUtil.ToTestableString(page[3].StagingDefault), true);
            Assert.AreEqual("/v2/security_groups/40512380-db93-4e89-85a3-64501ce8a802/spaces", TestUtil.ToTestableString(page[3].SpacesUrl), true);
            Assert.AreEqual("5e1c030b-fde8-4a91-a20c-cc8b4aedf470", TestUtil.ToTestableString(page[4].EntityMetadata.Guid), true);
            Assert.AreEqual("/v2/security_groups/5e1c030b-fde8-4a91-a20c-cc8b4aedf470", TestUtil.ToTestableString(page[4].EntityMetadata.Url), true);
            Assert.AreEqual("2016-02-05T12:14:49Z", TestUtil.ToTestableString(page[4].EntityMetadata.CreatedAt), true);
            Assert.AreEqual("", TestUtil.ToTestableString(page[4].EntityMetadata.UpdatedAt), true);
            Assert.AreEqual("name-1820", TestUtil.ToTestableString(page[4].Name), true);
            Assert.AreEqual("false", TestUtil.ToTestableString(page[4].RunningDefault), true);
            Assert.AreEqual("false", TestUtil.ToTestableString(page[4].StagingDefault), true);
            Assert.AreEqual("/v2/security_groups/5e1c030b-fde8-4a91-a20c-cc8b4aedf470/spaces", TestUtil.ToTestableString(page[4].SpacesUrl), true);
        }

        [TestMethod]
        public void TestRemoveSpaceFromSecurityGroupResponse()
        {
            string json = @"{
  ""metadata"": {
    ""guid"": ""bc3aa061-025a-45f6-8674-6a69944c42a9"",
    ""url"": ""/v2/security_groups/bc3aa061-025a-45f6-8674-6a69944c42a9"",
    ""created_at"": ""2016-02-05T12:14:47Z"",
    ""updated_at"": null
  },
  ""entity"": {
    ""name"": ""dummy1"",
    ""rules"": [

    ],
    ""running_default"": false,
    ""staging_default"": false,
    ""spaces_url"": ""/v2/security_groups/bc3aa061-025a-45f6-8674-6a69944c42a9/spaces""
  }
}";

            RemoveSpaceFromSecurityGroupResponse obj = Utilities.DeserializeJson<RemoveSpaceFromSecurityGroupResponse>(json);

            Assert.AreEqual("bc3aa061-025a-45f6-8674-6a69944c42a9", TestUtil.ToTestableString(obj.EntityMetadata.Guid), true);
            Assert.AreEqual("/v2/security_groups/bc3aa061-025a-45f6-8674-6a69944c42a9", TestUtil.ToTestableString(obj.EntityMetadata.Url), true);
            Assert.AreEqual("2016-02-05T12:14:47Z", TestUtil.ToTestableString(obj.EntityMetadata.CreatedAt), true);
            Assert.AreEqual("", TestUtil.ToTestableString(obj.EntityMetadata.UpdatedAt), true);
            Assert.AreEqual("dummy1", TestUtil.ToTestableString(obj.Name), true);
            Assert.AreEqual("false", TestUtil.ToTestableString(obj.RunningDefault), true);
            Assert.AreEqual("false", TestUtil.ToTestableString(obj.StagingDefault), true);
            Assert.AreEqual("/v2/security_groups/bc3aa061-025a-45f6-8674-6a69944c42a9/spaces", TestUtil.ToTestableString(obj.SpacesUrl), true);
        }

        [TestMethod]
        public void TestAssociateSpaceWithSecurityGroupResponse()
        {
            string json = @"{
  ""metadata"": {
    ""guid"": ""bc3aa061-025a-45f6-8674-6a69944c42a9"",
    ""url"": ""/v2/security_groups/bc3aa061-025a-45f6-8674-6a69944c42a9"",
    ""created_at"": ""2016-02-05T12:14:47Z"",
    ""updated_at"": null
  },
  ""entity"": {
    ""name"": ""dummy1"",
    ""rules"": [

    ],
    ""running_default"": false,
    ""staging_default"": false,
    ""spaces_url"": ""/v2/security_groups/bc3aa061-025a-45f6-8674-6a69944c42a9/spaces""
  }
}";

            AssociateSpaceWithSecurityGroupResponse obj = Utilities.DeserializeJson<AssociateSpaceWithSecurityGroupResponse>(json);

            Assert.AreEqual("bc3aa061-025a-45f6-8674-6a69944c42a9", TestUtil.ToTestableString(obj.EntityMetadata.Guid), true);
            Assert.AreEqual("/v2/security_groups/bc3aa061-025a-45f6-8674-6a69944c42a9", TestUtil.ToTestableString(obj.EntityMetadata.Url), true);
            Assert.AreEqual("2016-02-05T12:14:47Z", TestUtil.ToTestableString(obj.EntityMetadata.CreatedAt), true);
            Assert.AreEqual("", TestUtil.ToTestableString(obj.EntityMetadata.UpdatedAt), true);
            Assert.AreEqual("dummy1", TestUtil.ToTestableString(obj.Name), true);
            Assert.AreEqual("false", TestUtil.ToTestableString(obj.RunningDefault), true);
            Assert.AreEqual("false", TestUtil.ToTestableString(obj.StagingDefault), true);
            Assert.AreEqual("/v2/security_groups/bc3aa061-025a-45f6-8674-6a69944c42a9/spaces", TestUtil.ToTestableString(obj.SpacesUrl), true);
        }

        [TestMethod]
        public void TestCreateSecurityGroupResponse()
        {
            string json = @"{
  ""metadata"": {
    ""guid"": ""c47c8f19-14b9-4991-bdca-4af1a8d72d5c"",
    ""url"": ""/v2/security_groups/c47c8f19-14b9-4991-bdca-4af1a8d72d5c"",
    ""created_at"": ""2016-02-05T12:14:49Z"",
    ""updated_at"": null
  },
  ""entity"": {
    ""name"": ""my_super_sec_group"",
    ""rules"": [
      {
        ""protocol"": ""icmp"",
        ""destination"": ""0.0.0.0/0"",
        ""type"": 0,
        ""code"": 1
      },
      {
        ""protocol"": ""tcp"",
        ""destination"": ""0.0.0.0/0"",
        ""ports"": ""2048-3000"",
        ""log"": true
      },
      {
        ""protocol"": ""udp"",
        ""destination"": ""0.0.0.0/0"",
        ""ports"": ""53, 5353""
      },
      {
        ""protocol"": ""all"",
        ""destination"": ""0.0.0.0/0""
      }
    ],
    ""running_default"": false,
    ""staging_default"": false,
    ""spaces_url"": ""/v2/security_groups/c47c8f19-14b9-4991-bdca-4af1a8d72d5c/spaces""
  }
}";

            CreateSecurityGroupResponse obj = Utilities.DeserializeJson<CreateSecurityGroupResponse>(json);

            Assert.AreEqual("c47c8f19-14b9-4991-bdca-4af1a8d72d5c", TestUtil.ToTestableString(obj.EntityMetadata.Guid), true);
            Assert.AreEqual("/v2/security_groups/c47c8f19-14b9-4991-bdca-4af1a8d72d5c", TestUtil.ToTestableString(obj.EntityMetadata.Url), true);
            Assert.AreEqual("2016-02-05T12:14:49Z", TestUtil.ToTestableString(obj.EntityMetadata.CreatedAt), true);
            Assert.AreEqual("", TestUtil.ToTestableString(obj.EntityMetadata.UpdatedAt), true);
            Assert.AreEqual("my_super_sec_group", TestUtil.ToTestableString(obj.Name), true);
            Assert.AreEqual("false", TestUtil.ToTestableString(obj.RunningDefault), true);
            Assert.AreEqual("false", TestUtil.ToTestableString(obj.StagingDefault), true);
            Assert.AreEqual("/v2/security_groups/c47c8f19-14b9-4991-bdca-4af1a8d72d5c/spaces", TestUtil.ToTestableString(obj.SpacesUrl), true);
        }

        [TestMethod]
        public void TestRetrieveSecurityGroupResponse()
        {
            string json = @"{
  ""metadata"": {
    ""guid"": ""bc3aa061-025a-45f6-8674-6a69944c42a9"",
    ""url"": ""/v2/security_groups/bc3aa061-025a-45f6-8674-6a69944c42a9"",
    ""created_at"": ""2016-02-05T12:14:47Z"",
    ""updated_at"": null
  },
  ""entity"": {
    ""name"": ""dummy1"",
    ""rules"": [

    ],
    ""running_default"": false,
    ""staging_default"": false,
    ""spaces_url"": ""/v2/security_groups/bc3aa061-025a-45f6-8674-6a69944c42a9/spaces""
  }
}";

            RetrieveSecurityGroupResponse obj = Utilities.DeserializeJson<RetrieveSecurityGroupResponse>(json);

            Assert.AreEqual("bc3aa061-025a-45f6-8674-6a69944c42a9", TestUtil.ToTestableString(obj.EntityMetadata.Guid), true);
            Assert.AreEqual("/v2/security_groups/bc3aa061-025a-45f6-8674-6a69944c42a9", TestUtil.ToTestableString(obj.EntityMetadata.Url), true);
            Assert.AreEqual("2016-02-05T12:14:47Z", TestUtil.ToTestableString(obj.EntityMetadata.CreatedAt), true);
            Assert.AreEqual("", TestUtil.ToTestableString(obj.EntityMetadata.UpdatedAt), true);
            Assert.AreEqual("dummy1", TestUtil.ToTestableString(obj.Name), true);
            Assert.AreEqual("false", TestUtil.ToTestableString(obj.RunningDefault), true);
            Assert.AreEqual("false", TestUtil.ToTestableString(obj.StagingDefault), true);
            Assert.AreEqual("/v2/security_groups/bc3aa061-025a-45f6-8674-6a69944c42a9/spaces", TestUtil.ToTestableString(obj.SpacesUrl), true);
        }

        [TestMethod]
        public void TestListAllSpacesForSecurityGroupResponse()
        {
            string json = @"{
  ""total_results"": 1,
  ""total_pages"": 1,
  ""prev_url"": null,
  ""next_url"": null,
  ""resources"": [
    {
      ""metadata"": {
        ""guid"": ""b76f73b5-3e2a-4e04-9c5d-c59843e4d326"",
        ""url"": ""/v2/spaces/b76f73b5-3e2a-4e04-9c5d-c59843e4d326"",
        ""created_at"": ""2016-02-05T12:14:49Z"",
        ""updated_at"": null
      },
      ""entity"": {
        ""name"": ""name-1830"",
        ""organization_guid"": ""6d89e3f2-2884-414f-bb8c-ac7b5fd2c42e"",
        ""space_quota_definition_guid"": null,
        ""allow_ssh"": true,
        ""organization_url"": ""/v2/organizations/6d89e3f2-2884-414f-bb8c-ac7b5fd2c42e"",
        ""developers_url"": ""/v2/spaces/b76f73b5-3e2a-4e04-9c5d-c59843e4d326/developers"",
        ""managers_url"": ""/v2/spaces/b76f73b5-3e2a-4e04-9c5d-c59843e4d326/managers"",
        ""auditors_url"": ""/v2/spaces/b76f73b5-3e2a-4e04-9c5d-c59843e4d326/auditors"",
        ""apps_url"": ""/v2/spaces/b76f73b5-3e2a-4e04-9c5d-c59843e4d326/apps"",
        ""routes_url"": ""/v2/spaces/b76f73b5-3e2a-4e04-9c5d-c59843e4d326/routes"",
        ""domains_url"": ""/v2/spaces/b76f73b5-3e2a-4e04-9c5d-c59843e4d326/domains"",
        ""service_instances_url"": ""/v2/spaces/b76f73b5-3e2a-4e04-9c5d-c59843e4d326/service_instances"",
        ""app_events_url"": ""/v2/spaces/b76f73b5-3e2a-4e04-9c5d-c59843e4d326/app_events"",
        ""events_url"": ""/v2/spaces/b76f73b5-3e2a-4e04-9c5d-c59843e4d326/events"",
        ""security_groups_url"": ""/v2/spaces/b76f73b5-3e2a-4e04-9c5d-c59843e4d326/security_groups""
      }
    }
  ]
}";

            PagedResponseCollection<ListAllSpacesForSecurityGroupResponse> page = Utilities.DeserializePage<ListAllSpacesForSecurityGroupResponse>(json, null);

            Assert.AreEqual("1", TestUtil.ToTestableString(page.Properties.TotalResults), true);
            Assert.AreEqual("1", TestUtil.ToTestableString(page.Properties.TotalPages), true);
            Assert.AreEqual("", TestUtil.ToTestableString(page.Properties.PreviousUrl), true);
            Assert.AreEqual("", TestUtil.ToTestableString(page.Properties.NextUrl), true);
            Assert.AreEqual("b76f73b5-3e2a-4e04-9c5d-c59843e4d326", TestUtil.ToTestableString(page[0].EntityMetadata.Guid), true);
            Assert.AreEqual("/v2/spaces/b76f73b5-3e2a-4e04-9c5d-c59843e4d326", TestUtil.ToTestableString(page[0].EntityMetadata.Url), true);
            Assert.AreEqual("2016-02-05T12:14:49Z", TestUtil.ToTestableString(page[0].EntityMetadata.CreatedAt), true);
            Assert.AreEqual("", TestUtil.ToTestableString(page[0].EntityMetadata.UpdatedAt), true);
            Assert.AreEqual("name-1830", TestUtil.ToTestableString(page[0].Name), true);
            Assert.AreEqual("6d89e3f2-2884-414f-bb8c-ac7b5fd2c42e", TestUtil.ToTestableString(page[0].OrganizationGuid), true);
            Assert.AreEqual("", TestUtil.ToTestableString(page[0].SpaceQuotaDefinitionGuid), true);
            Assert.AreEqual("true", TestUtil.ToTestableString(page[0].AllowSsh), true);
            Assert.AreEqual("/v2/organizations/6d89e3f2-2884-414f-bb8c-ac7b5fd2c42e", TestUtil.ToTestableString(page[0].OrganizationUrl), true);
            Assert.AreEqual("/v2/spaces/b76f73b5-3e2a-4e04-9c5d-c59843e4d326/developers", TestUtil.ToTestableString(page[0].DevelopersUrl), true);
            Assert.AreEqual("/v2/spaces/b76f73b5-3e2a-4e04-9c5d-c59843e4d326/managers", TestUtil.ToTestableString(page[0].ManagersUrl), true);
            Assert.AreEqual("/v2/spaces/b76f73b5-3e2a-4e04-9c5d-c59843e4d326/auditors", TestUtil.ToTestableString(page[0].AuditorsUrl), true);
            Assert.AreEqual("/v2/spaces/b76f73b5-3e2a-4e04-9c5d-c59843e4d326/apps", TestUtil.ToTestableString(page[0].AppsUrl), true);
            Assert.AreEqual("/v2/spaces/b76f73b5-3e2a-4e04-9c5d-c59843e4d326/routes", TestUtil.ToTestableString(page[0].RoutesUrl), true);
            Assert.AreEqual("/v2/spaces/b76f73b5-3e2a-4e04-9c5d-c59843e4d326/domains", TestUtil.ToTestableString(page[0].DomainsUrl), true);
            Assert.AreEqual("/v2/spaces/b76f73b5-3e2a-4e04-9c5d-c59843e4d326/service_instances", TestUtil.ToTestableString(page[0].ServiceInstancesUrl), true);
            Assert.AreEqual("/v2/spaces/b76f73b5-3e2a-4e04-9c5d-c59843e4d326/app_events", TestUtil.ToTestableString(page[0].AppEventsUrl), true);
            Assert.AreEqual("/v2/spaces/b76f73b5-3e2a-4e04-9c5d-c59843e4d326/events", TestUtil.ToTestableString(page[0].EventsUrl), true);
            Assert.AreEqual("/v2/spaces/b76f73b5-3e2a-4e04-9c5d-c59843e4d326/security_groups", TestUtil.ToTestableString(page[0].SecurityGroupsUrl), true);
        }
    }
}
