//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

//
// This source code was auto-generated by cf-sdk-builder
//

using CloudFoundry.CloudController.V2.Client;
using CloudFoundry.CloudController.V2.Client.Data;
using Microsoft.CSharp;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System.CodeDom.Compiler;

namespace CloudFoundry.CloudController.V2.Test.Deserialization
{
    [TestClass]
    [GeneratedCodeAttribute("cf-sdk-builder", "1.0.0.0")]
    public class SecurityGroupsTest
    {


        [TestMethod]
        public void TestRetrieveSecurityGroupResponse()
        {
            string json = @"{
  ""metadata"": {
    ""guid"": ""f0f07510-02b9-45eb-85b5-b2f6e6375104"",
    ""url"": ""/v2/security_groups/f0f07510-02b9-45eb-85b5-b2f6e6375104"",
    ""created_at"": ""2015-07-29T12:47:17Z"",
    ""updated_at"": null
  },
  ""entity"": {
    ""name"": ""dummy1"",
    ""rules"": [

    ],
    ""running_default"": false,
    ""staging_default"": false,
    ""spaces_url"": ""/v2/security_groups/f0f07510-02b9-45eb-85b5-b2f6e6375104/spaces""
  }
}";

            RetrieveSecurityGroupResponse obj = Utilities.DeserializeJson<RetrieveSecurityGroupResponse>(json);

            Assert.AreEqual("f0f07510-02b9-45eb-85b5-b2f6e6375104", TestUtil.ToTestableString(obj.EntityMetadata.Guid), true);
            Assert.AreEqual("/v2/security_groups/f0f07510-02b9-45eb-85b5-b2f6e6375104", TestUtil.ToTestableString(obj.EntityMetadata.Url), true);
            Assert.AreEqual("2015-07-29T12:47:17Z", TestUtil.ToTestableString(obj.EntityMetadata.CreatedAt), true);
            Assert.AreEqual("", TestUtil.ToTestableString(obj.EntityMetadata.UpdatedAt), true);
            Assert.AreEqual("dummy1", TestUtil.ToTestableString(obj.Name), true);
            Assert.AreEqual("false", TestUtil.ToTestableString(obj.RunningDefault), true);
            Assert.AreEqual("false", TestUtil.ToTestableString(obj.StagingDefault), true);
            Assert.AreEqual("/v2/security_groups/f0f07510-02b9-45eb-85b5-b2f6e6375104/spaces", TestUtil.ToTestableString(obj.SpacesUrl), true);
        }

        [TestMethod]
        public void TestAssociateSpaceWithSecurityGroupResponse()
        {
            string json = @"{
  ""metadata"": {
    ""guid"": ""f0f07510-02b9-45eb-85b5-b2f6e6375104"",
    ""url"": ""/v2/security_groups/f0f07510-02b9-45eb-85b5-b2f6e6375104"",
    ""created_at"": ""2015-07-29T12:47:17Z"",
    ""updated_at"": null
  },
  ""entity"": {
    ""name"": ""dummy1"",
    ""rules"": [

    ],
    ""running_default"": false,
    ""staging_default"": false,
    ""spaces_url"": ""/v2/security_groups/f0f07510-02b9-45eb-85b5-b2f6e6375104/spaces""
  }
}";

            AssociateSpaceWithSecurityGroupResponse obj = Utilities.DeserializeJson<AssociateSpaceWithSecurityGroupResponse>(json);

            Assert.AreEqual("f0f07510-02b9-45eb-85b5-b2f6e6375104", TestUtil.ToTestableString(obj.EntityMetadata.Guid), true);
            Assert.AreEqual("/v2/security_groups/f0f07510-02b9-45eb-85b5-b2f6e6375104", TestUtil.ToTestableString(obj.EntityMetadata.Url), true);
            Assert.AreEqual("2015-07-29T12:47:17Z", TestUtil.ToTestableString(obj.EntityMetadata.CreatedAt), true);
            Assert.AreEqual("", TestUtil.ToTestableString(obj.EntityMetadata.UpdatedAt), true);
            Assert.AreEqual("dummy1", TestUtil.ToTestableString(obj.Name), true);
            Assert.AreEqual("false", TestUtil.ToTestableString(obj.RunningDefault), true);
            Assert.AreEqual("false", TestUtil.ToTestableString(obj.StagingDefault), true);
            Assert.AreEqual("/v2/security_groups/f0f07510-02b9-45eb-85b5-b2f6e6375104/spaces", TestUtil.ToTestableString(obj.SpacesUrl), true);
        }

        [TestMethod]
        public void TestListAllSpacesForSecurityGroupResponse()
        {
            string json = @"{
  ""total_results"": 1,
  ""total_pages"": 1,
  ""prev_url"": null,
  ""next_url"": null,
  ""resources"": [
    {
      ""metadata"": {
        ""guid"": ""9756621b-12f5-421b-a197-4535d598cd9e"",
        ""url"": ""/v2/spaces/9756621b-12f5-421b-a197-4535d598cd9e"",
        ""created_at"": ""2015-07-29T12:47:25Z"",
        ""updated_at"": null
      },
      ""entity"": {
        ""name"": ""name-1753"",
        ""organization_guid"": ""34e1711b-6443-4ca2-a056-b23ba996a7a0"",
        ""space_quota_definition_guid"": null,
        ""allow_ssh"": true,
        ""organization_url"": ""/v2/organizations/34e1711b-6443-4ca2-a056-b23ba996a7a0"",
        ""developers_url"": ""/v2/spaces/9756621b-12f5-421b-a197-4535d598cd9e/developers"",
        ""managers_url"": ""/v2/spaces/9756621b-12f5-421b-a197-4535d598cd9e/managers"",
        ""auditors_url"": ""/v2/spaces/9756621b-12f5-421b-a197-4535d598cd9e/auditors"",
        ""apps_url"": ""/v2/spaces/9756621b-12f5-421b-a197-4535d598cd9e/apps"",
        ""routes_url"": ""/v2/spaces/9756621b-12f5-421b-a197-4535d598cd9e/routes"",
        ""domains_url"": ""/v2/spaces/9756621b-12f5-421b-a197-4535d598cd9e/domains"",
        ""service_instances_url"": ""/v2/spaces/9756621b-12f5-421b-a197-4535d598cd9e/service_instances"",
        ""app_events_url"": ""/v2/spaces/9756621b-12f5-421b-a197-4535d598cd9e/app_events"",
        ""events_url"": ""/v2/spaces/9756621b-12f5-421b-a197-4535d598cd9e/events"",
        ""security_groups_url"": ""/v2/spaces/9756621b-12f5-421b-a197-4535d598cd9e/security_groups""
      }
    }
  ]
}";

            PagedResponseCollection<ListAllSpacesForSecurityGroupResponse> page = Utilities.DeserializePage<ListAllSpacesForSecurityGroupResponse>(json, null);

            Assert.AreEqual("1", TestUtil.ToTestableString(page.Properties.TotalResults), true);
            Assert.AreEqual("1", TestUtil.ToTestableString(page.Properties.TotalPages), true);
            Assert.AreEqual("", TestUtil.ToTestableString(page.Properties.PreviousUrl), true);
            Assert.AreEqual("", TestUtil.ToTestableString(page.Properties.NextUrl), true);
            Assert.AreEqual("9756621b-12f5-421b-a197-4535d598cd9e", TestUtil.ToTestableString(page[0].EntityMetadata.Guid), true);
            Assert.AreEqual("/v2/spaces/9756621b-12f5-421b-a197-4535d598cd9e", TestUtil.ToTestableString(page[0].EntityMetadata.Url), true);
            Assert.AreEqual("2015-07-29T12:47:25Z", TestUtil.ToTestableString(page[0].EntityMetadata.CreatedAt), true);
            Assert.AreEqual("", TestUtil.ToTestableString(page[0].EntityMetadata.UpdatedAt), true);
            Assert.AreEqual("name-1753", TestUtil.ToTestableString(page[0].Name), true);
            Assert.AreEqual("34e1711b-6443-4ca2-a056-b23ba996a7a0", TestUtil.ToTestableString(page[0].OrganizationGuid), true);
            Assert.AreEqual("", TestUtil.ToTestableString(page[0].SpaceQuotaDefinitionGuid), true);
            Assert.AreEqual("true", TestUtil.ToTestableString(page[0].AllowSsh), true);
            Assert.AreEqual("/v2/organizations/34e1711b-6443-4ca2-a056-b23ba996a7a0", TestUtil.ToTestableString(page[0].OrganizationUrl), true);
            Assert.AreEqual("/v2/spaces/9756621b-12f5-421b-a197-4535d598cd9e/developers", TestUtil.ToTestableString(page[0].DevelopersUrl), true);
            Assert.AreEqual("/v2/spaces/9756621b-12f5-421b-a197-4535d598cd9e/managers", TestUtil.ToTestableString(page[0].ManagersUrl), true);
            Assert.AreEqual("/v2/spaces/9756621b-12f5-421b-a197-4535d598cd9e/auditors", TestUtil.ToTestableString(page[0].AuditorsUrl), true);
            Assert.AreEqual("/v2/spaces/9756621b-12f5-421b-a197-4535d598cd9e/apps", TestUtil.ToTestableString(page[0].AppsUrl), true);
            Assert.AreEqual("/v2/spaces/9756621b-12f5-421b-a197-4535d598cd9e/routes", TestUtil.ToTestableString(page[0].RoutesUrl), true);
            Assert.AreEqual("/v2/spaces/9756621b-12f5-421b-a197-4535d598cd9e/domains", TestUtil.ToTestableString(page[0].DomainsUrl), true);
            Assert.AreEqual("/v2/spaces/9756621b-12f5-421b-a197-4535d598cd9e/service_instances", TestUtil.ToTestableString(page[0].ServiceInstancesUrl), true);
            Assert.AreEqual("/v2/spaces/9756621b-12f5-421b-a197-4535d598cd9e/app_events", TestUtil.ToTestableString(page[0].AppEventsUrl), true);
            Assert.AreEqual("/v2/spaces/9756621b-12f5-421b-a197-4535d598cd9e/events", TestUtil.ToTestableString(page[0].EventsUrl), true);
            Assert.AreEqual("/v2/spaces/9756621b-12f5-421b-a197-4535d598cd9e/security_groups", TestUtil.ToTestableString(page[0].SecurityGroupsUrl), true);
        }

        [TestMethod]
        public void TestUpdateSecurityGroupResponse()
        {
            string json = @"{
  ""metadata"": {
    ""guid"": ""f0f07510-02b9-45eb-85b5-b2f6e6375104"",
    ""url"": ""/v2/security_groups/f0f07510-02b9-45eb-85b5-b2f6e6375104"",
    ""created_at"": ""2015-07-29T12:47:17Z"",
    ""updated_at"": ""2015-07-29T12:47:25Z""
  },
  ""entity"": {
    ""name"": ""new_name"",
    ""rules"": [

    ],
    ""running_default"": false,
    ""staging_default"": false,
    ""spaces_url"": ""/v2/security_groups/f0f07510-02b9-45eb-85b5-b2f6e6375104/spaces""
  }
}";

            UpdateSecurityGroupResponse obj = Utilities.DeserializeJson<UpdateSecurityGroupResponse>(json);

            Assert.AreEqual("f0f07510-02b9-45eb-85b5-b2f6e6375104", TestUtil.ToTestableString(obj.EntityMetadata.Guid), true);
            Assert.AreEqual("/v2/security_groups/f0f07510-02b9-45eb-85b5-b2f6e6375104", TestUtil.ToTestableString(obj.EntityMetadata.Url), true);
            Assert.AreEqual("2015-07-29T12:47:17Z", TestUtil.ToTestableString(obj.EntityMetadata.CreatedAt), true);
            Assert.AreEqual("2015-07-29T12:47:25Z", TestUtil.ToTestableString(obj.EntityMetadata.UpdatedAt), true);
            Assert.AreEqual("new_name", TestUtil.ToTestableString(obj.Name), true);
            Assert.AreEqual("false", TestUtil.ToTestableString(obj.RunningDefault), true);
            Assert.AreEqual("false", TestUtil.ToTestableString(obj.StagingDefault), true);
            Assert.AreEqual("/v2/security_groups/f0f07510-02b9-45eb-85b5-b2f6e6375104/spaces", TestUtil.ToTestableString(obj.SpacesUrl), true);
        }

        [TestMethod]
        public void TestListAllSecurityGroupsResponse()
        {
            string json = @"{
  ""total_results"": 5,
  ""total_pages"": 1,
  ""prev_url"": null,
  ""next_url"": null,
  ""resources"": [
    {
      ""metadata"": {
        ""guid"": ""f0f07510-02b9-45eb-85b5-b2f6e6375104"",
        ""url"": ""/v2/security_groups/f0f07510-02b9-45eb-85b5-b2f6e6375104"",
        ""created_at"": ""2015-07-29T12:47:17Z"",
        ""updated_at"": null
      },
      ""entity"": {
        ""name"": ""dummy1"",
        ""rules"": [

        ],
        ""running_default"": false,
        ""staging_default"": false,
        ""spaces_url"": ""/v2/security_groups/f0f07510-02b9-45eb-85b5-b2f6e6375104/spaces""
      }
    },
    {
      ""metadata"": {
        ""guid"": ""140468c8-37e2-49de-a7fd-282c156a59f9"",
        ""url"": ""/v2/security_groups/140468c8-37e2-49de-a7fd-282c156a59f9"",
        ""created_at"": ""2015-07-29T12:47:17Z"",
        ""updated_at"": null
      },
      ""entity"": {
        ""name"": ""dummy2"",
        ""rules"": [

        ],
        ""running_default"": false,
        ""staging_default"": false,
        ""spaces_url"": ""/v2/security_groups/140468c8-37e2-49de-a7fd-282c156a59f9/spaces""
      }
    },
    {
      ""metadata"": {
        ""guid"": ""1ece76ea-e095-4c3b-910e-4de9336fd712"",
        ""url"": ""/v2/security_groups/1ece76ea-e095-4c3b-910e-4de9336fd712"",
        ""created_at"": ""2015-07-29T12:47:25Z"",
        ""updated_at"": null
      },
      ""entity"": {
        ""name"": ""name-1756"",
        ""rules"": [
          {
            ""protocol"": ""udp"",
            ""ports"": ""8080"",
            ""destination"": ""198.41.191.47/1""
          }
        ],
        ""running_default"": false,
        ""staging_default"": false,
        ""spaces_url"": ""/v2/security_groups/1ece76ea-e095-4c3b-910e-4de9336fd712/spaces""
      }
    },
    {
      ""metadata"": {
        ""guid"": ""52247725-d2fc-457a-a093-a40c074e9a56"",
        ""url"": ""/v2/security_groups/52247725-d2fc-457a-a093-a40c074e9a56"",
        ""created_at"": ""2015-07-29T12:47:25Z"",
        ""updated_at"": null
      },
      ""entity"": {
        ""name"": ""name-1757"",
        ""rules"": [
          {
            ""protocol"": ""udp"",
            ""ports"": ""8080"",
            ""destination"": ""198.41.191.47/1""
          }
        ],
        ""running_default"": false,
        ""staging_default"": false,
        ""spaces_url"": ""/v2/security_groups/52247725-d2fc-457a-a093-a40c074e9a56/spaces""
      }
    },
    {
      ""metadata"": {
        ""guid"": ""c81a0d86-bdac-4fe3-beca-be9aa600bd82"",
        ""url"": ""/v2/security_groups/c81a0d86-bdac-4fe3-beca-be9aa600bd82"",
        ""created_at"": ""2015-07-29T12:47:25Z"",
        ""updated_at"": null
      },
      ""entity"": {
        ""name"": ""name-1758"",
        ""rules"": [
          {
            ""protocol"": ""udp"",
            ""ports"": ""8080"",
            ""destination"": ""198.41.191.47/1""
          }
        ],
        ""running_default"": false,
        ""staging_default"": false,
        ""spaces_url"": ""/v2/security_groups/c81a0d86-bdac-4fe3-beca-be9aa600bd82/spaces""
      }
    }
  ]
}";

            PagedResponseCollection<ListAllSecurityGroupsResponse> page = Utilities.DeserializePage<ListAllSecurityGroupsResponse>(json, null);

            Assert.AreEqual("5", TestUtil.ToTestableString(page.Properties.TotalResults), true);
            Assert.AreEqual("1", TestUtil.ToTestableString(page.Properties.TotalPages), true);
            Assert.AreEqual("", TestUtil.ToTestableString(page.Properties.PreviousUrl), true);
            Assert.AreEqual("", TestUtil.ToTestableString(page.Properties.NextUrl), true);
            Assert.AreEqual("f0f07510-02b9-45eb-85b5-b2f6e6375104", TestUtil.ToTestableString(page[0].EntityMetadata.Guid), true);
            Assert.AreEqual("/v2/security_groups/f0f07510-02b9-45eb-85b5-b2f6e6375104", TestUtil.ToTestableString(page[0].EntityMetadata.Url), true);
            Assert.AreEqual("2015-07-29T12:47:17Z", TestUtil.ToTestableString(page[0].EntityMetadata.CreatedAt), true);
            Assert.AreEqual("", TestUtil.ToTestableString(page[0].EntityMetadata.UpdatedAt), true);
            Assert.AreEqual("dummy1", TestUtil.ToTestableString(page[0].Name), true);
            Assert.AreEqual("false", TestUtil.ToTestableString(page[0].RunningDefault), true);
            Assert.AreEqual("false", TestUtil.ToTestableString(page[0].StagingDefault), true);
            Assert.AreEqual("/v2/security_groups/f0f07510-02b9-45eb-85b5-b2f6e6375104/spaces", TestUtil.ToTestableString(page[0].SpacesUrl), true);
            Assert.AreEqual("140468c8-37e2-49de-a7fd-282c156a59f9", TestUtil.ToTestableString(page[1].EntityMetadata.Guid), true);
            Assert.AreEqual("/v2/security_groups/140468c8-37e2-49de-a7fd-282c156a59f9", TestUtil.ToTestableString(page[1].EntityMetadata.Url), true);
            Assert.AreEqual("2015-07-29T12:47:17Z", TestUtil.ToTestableString(page[1].EntityMetadata.CreatedAt), true);
            Assert.AreEqual("", TestUtil.ToTestableString(page[1].EntityMetadata.UpdatedAt), true);
            Assert.AreEqual("dummy2", TestUtil.ToTestableString(page[1].Name), true);
            Assert.AreEqual("false", TestUtil.ToTestableString(page[1].RunningDefault), true);
            Assert.AreEqual("false", TestUtil.ToTestableString(page[1].StagingDefault), true);
            Assert.AreEqual("/v2/security_groups/140468c8-37e2-49de-a7fd-282c156a59f9/spaces", TestUtil.ToTestableString(page[1].SpacesUrl), true);
            Assert.AreEqual("1ece76ea-e095-4c3b-910e-4de9336fd712", TestUtil.ToTestableString(page[2].EntityMetadata.Guid), true);
            Assert.AreEqual("/v2/security_groups/1ece76ea-e095-4c3b-910e-4de9336fd712", TestUtil.ToTestableString(page[2].EntityMetadata.Url), true);
            Assert.AreEqual("2015-07-29T12:47:25Z", TestUtil.ToTestableString(page[2].EntityMetadata.CreatedAt), true);
            Assert.AreEqual("", TestUtil.ToTestableString(page[2].EntityMetadata.UpdatedAt), true);
            Assert.AreEqual("name-1756", TestUtil.ToTestableString(page[2].Name), true);
            Assert.AreEqual("false", TestUtil.ToTestableString(page[2].RunningDefault), true);
            Assert.AreEqual("false", TestUtil.ToTestableString(page[2].StagingDefault), true);
            Assert.AreEqual("/v2/security_groups/1ece76ea-e095-4c3b-910e-4de9336fd712/spaces", TestUtil.ToTestableString(page[2].SpacesUrl), true);
            Assert.AreEqual("52247725-d2fc-457a-a093-a40c074e9a56", TestUtil.ToTestableString(page[3].EntityMetadata.Guid), true);
            Assert.AreEqual("/v2/security_groups/52247725-d2fc-457a-a093-a40c074e9a56", TestUtil.ToTestableString(page[3].EntityMetadata.Url), true);
            Assert.AreEqual("2015-07-29T12:47:25Z", TestUtil.ToTestableString(page[3].EntityMetadata.CreatedAt), true);
            Assert.AreEqual("", TestUtil.ToTestableString(page[3].EntityMetadata.UpdatedAt), true);
            Assert.AreEqual("name-1757", TestUtil.ToTestableString(page[3].Name), true);
            Assert.AreEqual("false", TestUtil.ToTestableString(page[3].RunningDefault), true);
            Assert.AreEqual("false", TestUtil.ToTestableString(page[3].StagingDefault), true);
            Assert.AreEqual("/v2/security_groups/52247725-d2fc-457a-a093-a40c074e9a56/spaces", TestUtil.ToTestableString(page[3].SpacesUrl), true);
            Assert.AreEqual("c81a0d86-bdac-4fe3-beca-be9aa600bd82", TestUtil.ToTestableString(page[4].EntityMetadata.Guid), true);
            Assert.AreEqual("/v2/security_groups/c81a0d86-bdac-4fe3-beca-be9aa600bd82", TestUtil.ToTestableString(page[4].EntityMetadata.Url), true);
            Assert.AreEqual("2015-07-29T12:47:25Z", TestUtil.ToTestableString(page[4].EntityMetadata.CreatedAt), true);
            Assert.AreEqual("", TestUtil.ToTestableString(page[4].EntityMetadata.UpdatedAt), true);
            Assert.AreEqual("name-1758", TestUtil.ToTestableString(page[4].Name), true);
            Assert.AreEqual("false", TestUtil.ToTestableString(page[4].RunningDefault), true);
            Assert.AreEqual("false", TestUtil.ToTestableString(page[4].StagingDefault), true);
            Assert.AreEqual("/v2/security_groups/c81a0d86-bdac-4fe3-beca-be9aa600bd82/spaces", TestUtil.ToTestableString(page[4].SpacesUrl), true);
        }

        [TestMethod]
        public void TestRemoveSpaceFromSecurityGroupResponse()
        {
            string json = @"{
  ""metadata"": {
    ""guid"": ""f0f07510-02b9-45eb-85b5-b2f6e6375104"",
    ""url"": ""/v2/security_groups/f0f07510-02b9-45eb-85b5-b2f6e6375104"",
    ""created_at"": ""2015-07-29T12:47:17Z"",
    ""updated_at"": null
  },
  ""entity"": {
    ""name"": ""dummy1"",
    ""rules"": [

    ],
    ""running_default"": false,
    ""staging_default"": false,
    ""spaces_url"": ""/v2/security_groups/f0f07510-02b9-45eb-85b5-b2f6e6375104/spaces""
  }
}";

            RemoveSpaceFromSecurityGroupResponse obj = Utilities.DeserializeJson<RemoveSpaceFromSecurityGroupResponse>(json);

            Assert.AreEqual("f0f07510-02b9-45eb-85b5-b2f6e6375104", TestUtil.ToTestableString(obj.EntityMetadata.Guid), true);
            Assert.AreEqual("/v2/security_groups/f0f07510-02b9-45eb-85b5-b2f6e6375104", TestUtil.ToTestableString(obj.EntityMetadata.Url), true);
            Assert.AreEqual("2015-07-29T12:47:17Z", TestUtil.ToTestableString(obj.EntityMetadata.CreatedAt), true);
            Assert.AreEqual("", TestUtil.ToTestableString(obj.EntityMetadata.UpdatedAt), true);
            Assert.AreEqual("dummy1", TestUtil.ToTestableString(obj.Name), true);
            Assert.AreEqual("false", TestUtil.ToTestableString(obj.RunningDefault), true);
            Assert.AreEqual("false", TestUtil.ToTestableString(obj.StagingDefault), true);
            Assert.AreEqual("/v2/security_groups/f0f07510-02b9-45eb-85b5-b2f6e6375104/spaces", TestUtil.ToTestableString(obj.SpacesUrl), true);
        }

        [TestMethod]
        public void TestCreateSecurityGroupResponse()
        {
            string json = @"{
  ""metadata"": {
    ""guid"": ""4aa61018-9811-4707-85c3-cb2b014bd058"",
    ""url"": ""/v2/security_groups/4aa61018-9811-4707-85c3-cb2b014bd058"",
    ""created_at"": ""2015-07-29T12:47:25Z"",
    ""updated_at"": null
  },
  ""entity"": {
    ""name"": ""my_super_sec_group"",
    ""rules"": [
      {
        ""protocol"": ""icmp"",
        ""destination"": ""0.0.0.0/0"",
        ""type"": 0,
        ""code"": 1
      },
      {
        ""protocol"": ""tcp"",
        ""destination"": ""0.0.0.0/0"",
        ""ports"": ""2048-3000"",
        ""log"": true
      },
      {
        ""protocol"": ""udp"",
        ""destination"": ""0.0.0.0/0"",
        ""ports"": ""53, 5353""
      },
      {
        ""protocol"": ""all"",
        ""destination"": ""0.0.0.0/0""
      }
    ],
    ""running_default"": false,
    ""staging_default"": false,
    ""spaces_url"": ""/v2/security_groups/4aa61018-9811-4707-85c3-cb2b014bd058/spaces""
  }
}";

            CreateSecurityGroupResponse obj = Utilities.DeserializeJson<CreateSecurityGroupResponse>(json);

            Assert.AreEqual("4aa61018-9811-4707-85c3-cb2b014bd058", TestUtil.ToTestableString(obj.EntityMetadata.Guid), true);
            Assert.AreEqual("/v2/security_groups/4aa61018-9811-4707-85c3-cb2b014bd058", TestUtil.ToTestableString(obj.EntityMetadata.Url), true);
            Assert.AreEqual("2015-07-29T12:47:25Z", TestUtil.ToTestableString(obj.EntityMetadata.CreatedAt), true);
            Assert.AreEqual("", TestUtil.ToTestableString(obj.EntityMetadata.UpdatedAt), true);
            Assert.AreEqual("my_super_sec_group", TestUtil.ToTestableString(obj.Name), true);
            Assert.AreEqual("false", TestUtil.ToTestableString(obj.RunningDefault), true);
            Assert.AreEqual("false", TestUtil.ToTestableString(obj.StagingDefault), true);
            Assert.AreEqual("/v2/security_groups/4aa61018-9811-4707-85c3-cb2b014bd058/spaces", TestUtil.ToTestableString(obj.SpacesUrl), true);
        }
    }
}
