//------------------------------------------------------------------------------
// <auto-generated>
  //     This code was generated by a tool.
  //
  //     Changes to this file may cause incorrect behavior and will be lost if
  //     the code is regenerated.
  // </auto-generated>
//------------------------------------------------------------------------------

//
// This source code was auto-generated by cf-sdk-builder
//

using CloudFoundry.CloudController.V2.Client.Data;
using Microsoft.QualityTools.Testing.Fakes;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System;
using System.CodeDom.Compiler;
using System.Net;
using System.Threading.Tasks;

namespace CloudFoundry.CloudController.V2.Client.Test.Fake
{
    [TestClass]
    [GeneratedCodeAttribute("cf-sdk-builder", "1.0.0.0")]
    public class ServiceKeysEndpoint
{
        [TestMethod]
        public void DeleteServiceKeyTest()
        {
            using (ShimsContext.Create())
            {
                MockClients clients = new MockClients();

                clients.ExpectedStatusCode = (HttpStatusCode)204;
                var cfClient = clients.CreateCloudFoundryClient();

                Guid? guid = Guid.NewGuid();


                cfClient.ServiceKeys.DeleteServiceKey(guid).Wait();

            }
        }

        [TestMethod]
        public void ListAllServiceKeysTest()
        {
            using (ShimsContext.Create())
            {
                MockClients clients = new MockClients();

                string json = @"{
  ""total_results"": 1,
  ""total_pages"": 1,
  ""prev_url"": null,
  ""next_url"": null,
  ""resources"": [
    {
      ""metadata"": {
        ""guid"": ""3b85a045-770d-4b5f-a45a-c7ad96c471a1"",
        ""url"": ""/v2/service_keys/3b85a045-770d-4b5f-a45a-c7ad96c471a1"",
        ""created_at"": ""2015-07-29T12:47:31Z"",
        ""updated_at"": null
      },
      ""entity"": {
        ""name"": ""name-2245"",
        ""service_instance_guid"": ""b1be4de9-2868-4c5e-820d-6f1bcfc26ba8"",
        ""credentials"": {
          ""creds-key-676"": ""creds-val-676""
        },
        ""service_instance_url"": ""/v2/service_instances/b1be4de9-2868-4c5e-820d-6f1bcfc26ba8""
      }
    }
  ]
}";
                clients.JsonResponse = json;

                clients.ExpectedStatusCode = (HttpStatusCode)200;
                var cfClient = clients.CreateCloudFoundryClient();


                var obj = cfClient.ServiceKeys.ListAllServiceKeys().Result;

                Assert.AreEqual("1", TestUtil.ToTestableString(obj.Properties.TotalResults), true);
                Assert.AreEqual("1", TestUtil.ToTestableString(obj.Properties.TotalPages), true);
                Assert.AreEqual("", TestUtil.ToTestableString(obj.Properties.PreviousUrl), true);
                Assert.AreEqual("", TestUtil.ToTestableString(obj.Properties.NextUrl), true);
                Assert.AreEqual("3b85a045-770d-4b5f-a45a-c7ad96c471a1", TestUtil.ToTestableString(obj[0].EntityMetadata.Guid), true);
                Assert.AreEqual("/v2/service_keys/3b85a045-770d-4b5f-a45a-c7ad96c471a1", TestUtil.ToTestableString(obj[0].EntityMetadata.Url), true);
                Assert.AreEqual("2015-07-29T12:47:31Z", TestUtil.ToTestableString(obj[0].EntityMetadata.CreatedAt), true);
                Assert.AreEqual("", TestUtil.ToTestableString(obj[0].EntityMetadata.UpdatedAt), true);
                Assert.AreEqual("name-2245", TestUtil.ToTestableString(obj[0].Name), true);
                Assert.AreEqual("b1be4de9-2868-4c5e-820d-6f1bcfc26ba8", TestUtil.ToTestableString(obj[0].ServiceInstanceGuid), true);
                Assert.AreEqual("/v2/service_instances/b1be4de9-2868-4c5e-820d-6f1bcfc26ba8", TestUtil.ToTestableString(obj[0].ServiceInstanceUrl), true);

            }
        }

        [TestMethod]
        public void CreateServiceKeyTest()
        {
            using (ShimsContext.Create())
            {
                MockClients clients = new MockClients();

                string json = @"{
  ""metadata"": {
    ""guid"": ""c448dfa3-8cbd-47a5-a3f8-897b06721640"",
    ""url"": ""/v2/service_keys/c448dfa3-8cbd-47a5-a3f8-897b06721640"",
    ""created_at"": ""2015-07-29T12:47:30Z"",
    ""updated_at"": null
  },
  ""entity"": {
    ""name"": ""name-2206"",
    ""service_instance_guid"": ""58b9c1b5-44d3-4c46-8aaf-cb55a6b57f8f"",
    ""credentials"": {
      ""creds-key-660"": ""creds-val-660""
    },
    ""service_instance_url"": ""/v2/service_instances/58b9c1b5-44d3-4c46-8aaf-cb55a6b57f8f""
  }
}";
                clients.JsonResponse = json;

                clients.ExpectedStatusCode = (HttpStatusCode)201;
                var cfClient = clients.CreateCloudFoundryClient();

                CreateServiceKeyRequest value = new CreateServiceKeyRequest();


                var obj = cfClient.ServiceKeys.CreateServiceKey(value).Result;


                Assert.AreEqual("c448dfa3-8cbd-47a5-a3f8-897b06721640", TestUtil.ToTestableString(obj.EntityMetadata.Guid), true);
                Assert.AreEqual("/v2/service_keys/c448dfa3-8cbd-47a5-a3f8-897b06721640", TestUtil.ToTestableString(obj.EntityMetadata.Url), true);
                Assert.AreEqual("2015-07-29T12:47:30Z", TestUtil.ToTestableString(obj.EntityMetadata.CreatedAt), true);
                Assert.AreEqual("", TestUtil.ToTestableString(obj.EntityMetadata.UpdatedAt), true);
                Assert.AreEqual("name-2206", TestUtil.ToTestableString(obj.Name), true);
                Assert.AreEqual("58b9c1b5-44d3-4c46-8aaf-cb55a6b57f8f", TestUtil.ToTestableString(obj.ServiceInstanceGuid), true);
                Assert.AreEqual("/v2/service_instances/58b9c1b5-44d3-4c46-8aaf-cb55a6b57f8f", TestUtil.ToTestableString(obj.ServiceInstanceUrl), true);

            }
        }

        [TestMethod]
        public void RetrieveServiceKeyTest()
        {
            using (ShimsContext.Create())
            {
                MockClients clients = new MockClients();

                string json = @"{
  ""metadata"": {
    ""guid"": ""110f2f78-9951-4df3-8c7d-d1fdcf0e94f7"",
    ""url"": ""/v2/service_keys/110f2f78-9951-4df3-8c7d-d1fdcf0e94f7"",
    ""created_at"": ""2015-07-29T12:47:30Z"",
    ""updated_at"": null
  },
  ""entity"": {
    ""name"": ""name-2232"",
    ""service_instance_guid"": ""015e27f2-e40c-482f-8552-403ec831ec95"",
    ""credentials"": {
      ""creds-key-671"": ""creds-val-671""
    },
    ""service_instance_url"": ""/v2/service_instances/015e27f2-e40c-482f-8552-403ec831ec95""
  }
}";
                clients.JsonResponse = json;

                clients.ExpectedStatusCode = (HttpStatusCode)200;
                var cfClient = clients.CreateCloudFoundryClient();

                Guid? guid = Guid.NewGuid();


                var obj = cfClient.ServiceKeys.RetrieveServiceKey(guid).Result;


                Assert.AreEqual("110f2f78-9951-4df3-8c7d-d1fdcf0e94f7", TestUtil.ToTestableString(obj.EntityMetadata.Guid), true);
                Assert.AreEqual("/v2/service_keys/110f2f78-9951-4df3-8c7d-d1fdcf0e94f7", TestUtil.ToTestableString(obj.EntityMetadata.Url), true);
                Assert.AreEqual("2015-07-29T12:47:30Z", TestUtil.ToTestableString(obj.EntityMetadata.CreatedAt), true);
                Assert.AreEqual("", TestUtil.ToTestableString(obj.EntityMetadata.UpdatedAt), true);
                Assert.AreEqual("name-2232", TestUtil.ToTestableString(obj.Name), true);
                Assert.AreEqual("015e27f2-e40c-482f-8552-403ec831ec95", TestUtil.ToTestableString(obj.ServiceInstanceGuid), true);
                Assert.AreEqual("/v2/service_instances/015e27f2-e40c-482f-8552-403ec831ec95", TestUtil.ToTestableString(obj.ServiceInstanceUrl), true);

            }
        }

    }
}