//------------------------------------------------------------------------------
// <auto-generated>
  //     This code was generated by a tool.
  //
  //     Changes to this file may cause incorrect behavior and will be lost if
  //     the code is regenerated.
  // </auto-generated>
//------------------------------------------------------------------------------

//
// This source code was auto-generated by cf-sdk-builder
//

using CloudFoundry.CloudController.V2.Client.Data;
using Microsoft.QualityTools.Testing.Fakes;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System;
using System.CodeDom.Compiler;
using System.Net;
using System.Threading.Tasks;

namespace CloudFoundry.CloudController.V2.Client.Test.Fake
{
    [TestClass]
    [GeneratedCodeAttribute("cf-sdk-builder", "1.0.0.0")]
    public class UserProvidedServiceInstancesEndpoint
{
        [TestMethod]
        public void UpdateUserProvidedServiceInstanceTest()
        {
            using (ShimsContext.Create())
            {
                MockClients clients = new MockClients();

                string json = @"{
  ""metadata"": {
    ""guid"": ""746d2d07-c8de-474c-bfc6-064ba5e9fb02"",
    ""url"": ""/v2/user_provided_service_instances/746d2d07-c8de-474c-bfc6-064ba5e9fb02"",
    ""created_at"": ""2016-02-05T12:14:40Z"",
    ""updated_at"": ""2016-02-05T12:14:40Z""
  },
  ""entity"": {
    ""name"": ""name-343"",
    ""credentials"": {
      ""somekey"": ""somenewvalue""
    },
    ""space_guid"": ""f4623114-24a8-4f23-ad02-d35956687267"",
    ""type"": ""user_provided_service_instance"",
    ""syslog_drain_url"": ""https://foo.com/url-4"",
    ""space_url"": ""/v2/spaces/f4623114-24a8-4f23-ad02-d35956687267"",
    ""service_bindings_url"": ""/v2/user_provided_service_instances/746d2d07-c8de-474c-bfc6-064ba5e9fb02/service_bindings""
  }
}";
                clients.JsonResponse = json;

                clients.ExpectedStatusCode = (HttpStatusCode)201;
                var cfClient = clients.CreateCloudFoundryClient();

                Guid? guid = Guid.NewGuid();

                UpdateUserProvidedServiceInstanceRequest value = new UpdateUserProvidedServiceInstanceRequest();


                var obj = cfClient.UserProvidedServiceInstances.UpdateUserProvidedServiceInstance(guid, value).Result;


                Assert.AreEqual("746d2d07-c8de-474c-bfc6-064ba5e9fb02", TestUtil.ToTestableString(obj.EntityMetadata.Guid), true);
                Assert.AreEqual("/v2/user_provided_service_instances/746d2d07-c8de-474c-bfc6-064ba5e9fb02", TestUtil.ToTestableString(obj.EntityMetadata.Url), true);
                Assert.AreEqual("2016-02-05T12:14:40Z", TestUtil.ToTestableString(obj.EntityMetadata.CreatedAt), true);
                Assert.AreEqual("2016-02-05T12:14:40Z", TestUtil.ToTestableString(obj.EntityMetadata.UpdatedAt), true);
                Assert.AreEqual("name-343", TestUtil.ToTestableString(obj.Name), true);
                Assert.AreEqual("f4623114-24a8-4f23-ad02-d35956687267", TestUtil.ToTestableString(obj.SpaceGuid), true);
                Assert.AreEqual("user_provided_service_instance", TestUtil.ToTestableString(obj.Type), true);
                Assert.AreEqual("https://foo.com/url-4", TestUtil.ToTestableString(obj.SyslogDrainUrl), true);
                Assert.AreEqual("/v2/spaces/f4623114-24a8-4f23-ad02-d35956687267", TestUtil.ToTestableString(obj.SpaceUrl), true);
                Assert.AreEqual("/v2/user_provided_service_instances/746d2d07-c8de-474c-bfc6-064ba5e9fb02/service_bindings", TestUtil.ToTestableString(obj.ServiceBindingsUrl), true);

            }
        }

        [TestMethod]
        public void DeleteUserProvidedServiceInstanceTest()
        {
            using (ShimsContext.Create())
            {
                MockClients clients = new MockClients();

                clients.ExpectedStatusCode = (HttpStatusCode)204;
                var cfClient = clients.CreateCloudFoundryClient();

                Guid? guid = Guid.NewGuid();


                cfClient.UserProvidedServiceInstances.DeleteUserProvidedServiceInstance(guid).Wait();

            }
        }

        [TestMethod]
        public void CreateUserProvidedServiceInstanceTest()
        {
            using (ShimsContext.Create())
            {
                MockClients clients = new MockClients();

                string json = @"{
  ""metadata"": {
    ""guid"": ""88ec3f89-60c3-41ce-925a-698dc7df1bc6"",
    ""url"": ""/v2/user_provided_service_instances/88ec3f89-60c3-41ce-925a-698dc7df1bc6"",
    ""created_at"": ""2016-02-05T12:14:40Z"",
    ""updated_at"": null
  },
  ""entity"": {
    ""name"": ""my-user-provided-instance"",
    ""credentials"": {
      ""somekey"": ""somevalue""
    },
    ""space_guid"": ""b66e3664-c5f7-43c1-8cdd-957c3b718f4a"",
    ""type"": ""user_provided_service_instance"",
    ""syslog_drain_url"": ""syslog://example.com"",
    ""space_url"": ""/v2/spaces/b66e3664-c5f7-43c1-8cdd-957c3b718f4a"",
    ""service_bindings_url"": ""/v2/user_provided_service_instances/88ec3f89-60c3-41ce-925a-698dc7df1bc6/service_bindings""
  }
}";
                clients.JsonResponse = json;

                clients.ExpectedStatusCode = (HttpStatusCode)201;
                var cfClient = clients.CreateCloudFoundryClient();

                CreateUserProvidedServiceInstanceRequest value = new CreateUserProvidedServiceInstanceRequest();


                var obj = cfClient.UserProvidedServiceInstances.CreateUserProvidedServiceInstance(value).Result;


                Assert.AreEqual("88ec3f89-60c3-41ce-925a-698dc7df1bc6", TestUtil.ToTestableString(obj.EntityMetadata.Guid), true);
                Assert.AreEqual("/v2/user_provided_service_instances/88ec3f89-60c3-41ce-925a-698dc7df1bc6", TestUtil.ToTestableString(obj.EntityMetadata.Url), true);
                Assert.AreEqual("2016-02-05T12:14:40Z", TestUtil.ToTestableString(obj.EntityMetadata.CreatedAt), true);
                Assert.AreEqual("", TestUtil.ToTestableString(obj.EntityMetadata.UpdatedAt), true);
                Assert.AreEqual("my-user-provided-instance", TestUtil.ToTestableString(obj.Name), true);
                Assert.AreEqual("b66e3664-c5f7-43c1-8cdd-957c3b718f4a", TestUtil.ToTestableString(obj.SpaceGuid), true);
                Assert.AreEqual("user_provided_service_instance", TestUtil.ToTestableString(obj.Type), true);
                Assert.AreEqual("syslog://example.com", TestUtil.ToTestableString(obj.SyslogDrainUrl), true);
                Assert.AreEqual("/v2/spaces/b66e3664-c5f7-43c1-8cdd-957c3b718f4a", TestUtil.ToTestableString(obj.SpaceUrl), true);
                Assert.AreEqual("/v2/user_provided_service_instances/88ec3f89-60c3-41ce-925a-698dc7df1bc6/service_bindings", TestUtil.ToTestableString(obj.ServiceBindingsUrl), true);

            }
        }

        [TestMethod]
        public void ListAllUserProvidedServiceInstancesTest()
        {
            using (ShimsContext.Create())
            {
                MockClients clients = new MockClients();

                string json = @"{
  ""total_results"": 1,
  ""total_pages"": 1,
  ""prev_url"": null,
  ""next_url"": null,
  ""resources"": [
    {
      ""metadata"": {
        ""guid"": ""8823daad-958d-4b57-9685-539dd56d4a23"",
        ""url"": ""/v2/user_provided_service_instances/8823daad-958d-4b57-9685-539dd56d4a23"",
        ""created_at"": ""2016-02-05T12:14:40Z"",
        ""updated_at"": null
      },
      ""entity"": {
        ""name"": ""name-351"",
        ""credentials"": {
          ""creds-key-156"": ""creds-val-156""
        },
        ""space_guid"": ""43143d20-d96f-416c-946b-6f41a8a89375"",
        ""type"": ""user_provided_service_instance"",
        ""syslog_drain_url"": ""https://foo.com/url-6"",
        ""space_url"": ""/v2/spaces/43143d20-d96f-416c-946b-6f41a8a89375"",
        ""service_bindings_url"": ""/v2/user_provided_service_instances/8823daad-958d-4b57-9685-539dd56d4a23/service_bindings""
      }
    }
  ]
}";
                clients.JsonResponse = json;

                clients.ExpectedStatusCode = (HttpStatusCode)200;
                var cfClient = clients.CreateCloudFoundryClient();


                var obj = cfClient.UserProvidedServiceInstances.ListAllUserProvidedServiceInstances().Result;

                Assert.AreEqual("1", TestUtil.ToTestableString(obj.Properties.TotalResults), true);
                Assert.AreEqual("1", TestUtil.ToTestableString(obj.Properties.TotalPages), true);
                Assert.AreEqual("", TestUtil.ToTestableString(obj.Properties.PreviousUrl), true);
                Assert.AreEqual("", TestUtil.ToTestableString(obj.Properties.NextUrl), true);
                Assert.AreEqual("8823daad-958d-4b57-9685-539dd56d4a23", TestUtil.ToTestableString(obj[0].EntityMetadata.Guid), true);
                Assert.AreEqual("/v2/user_provided_service_instances/8823daad-958d-4b57-9685-539dd56d4a23", TestUtil.ToTestableString(obj[0].EntityMetadata.Url), true);
                Assert.AreEqual("2016-02-05T12:14:40Z", TestUtil.ToTestableString(obj[0].EntityMetadata.CreatedAt), true);
                Assert.AreEqual("", TestUtil.ToTestableString(obj[0].EntityMetadata.UpdatedAt), true);
                Assert.AreEqual("name-351", TestUtil.ToTestableString(obj[0].Name), true);
                Assert.AreEqual("43143d20-d96f-416c-946b-6f41a8a89375", TestUtil.ToTestableString(obj[0].SpaceGuid), true);
                Assert.AreEqual("user_provided_service_instance", TestUtil.ToTestableString(obj[0].Type), true);
                Assert.AreEqual("https://foo.com/url-6", TestUtil.ToTestableString(obj[0].SyslogDrainUrl), true);
                Assert.AreEqual("/v2/spaces/43143d20-d96f-416c-946b-6f41a8a89375", TestUtil.ToTestableString(obj[0].SpaceUrl), true);
                Assert.AreEqual("/v2/user_provided_service_instances/8823daad-958d-4b57-9685-539dd56d4a23/service_bindings", TestUtil.ToTestableString(obj[0].ServiceBindingsUrl), true);

            }
        }

        [TestMethod]
        public void RetrieveUserProvidedServiceInstanceTest()
        {
            using (ShimsContext.Create())
            {
                MockClients clients = new MockClients();

                string json = @"{
  ""metadata"": {
    ""guid"": ""c375422c-517a-4e24-8c7a-34e65d6c5f77"",
    ""url"": ""/v2/user_provided_service_instances/c375422c-517a-4e24-8c7a-34e65d6c5f77"",
    ""created_at"": ""2016-02-05T12:14:40Z"",
    ""updated_at"": null
  },
  ""entity"": {
    ""name"": ""name-355"",
    ""credentials"": {
      ""creds-key-159"": ""creds-val-159""
    },
    ""space_guid"": ""84a1b099-01d4-41c0-b38c-025e4bef0acf"",
    ""type"": ""user_provided_service_instance"",
    ""syslog_drain_url"": ""https://foo.com/url-7"",
    ""space_url"": ""/v2/spaces/84a1b099-01d4-41c0-b38c-025e4bef0acf"",
    ""service_bindings_url"": ""/v2/user_provided_service_instances/c375422c-517a-4e24-8c7a-34e65d6c5f77/service_bindings""
  }
}";
                clients.JsonResponse = json;

                clients.ExpectedStatusCode = (HttpStatusCode)200;
                var cfClient = clients.CreateCloudFoundryClient();

                Guid? guid = Guid.NewGuid();


                var obj = cfClient.UserProvidedServiceInstances.RetrieveUserProvidedServiceInstance(guid).Result;


                Assert.AreEqual("c375422c-517a-4e24-8c7a-34e65d6c5f77", TestUtil.ToTestableString(obj.EntityMetadata.Guid), true);
                Assert.AreEqual("/v2/user_provided_service_instances/c375422c-517a-4e24-8c7a-34e65d6c5f77", TestUtil.ToTestableString(obj.EntityMetadata.Url), true);
                Assert.AreEqual("2016-02-05T12:14:40Z", TestUtil.ToTestableString(obj.EntityMetadata.CreatedAt), true);
                Assert.AreEqual("", TestUtil.ToTestableString(obj.EntityMetadata.UpdatedAt), true);
                Assert.AreEqual("name-355", TestUtil.ToTestableString(obj.Name), true);
                Assert.AreEqual("84a1b099-01d4-41c0-b38c-025e4bef0acf", TestUtil.ToTestableString(obj.SpaceGuid), true);
                Assert.AreEqual("user_provided_service_instance", TestUtil.ToTestableString(obj.Type), true);
                Assert.AreEqual("https://foo.com/url-7", TestUtil.ToTestableString(obj.SyslogDrainUrl), true);
                Assert.AreEqual("/v2/spaces/84a1b099-01d4-41c0-b38c-025e4bef0acf", TestUtil.ToTestableString(obj.SpaceUrl), true);
                Assert.AreEqual("/v2/user_provided_service_instances/c375422c-517a-4e24-8c7a-34e65d6c5f77/service_bindings", TestUtil.ToTestableString(obj.ServiceBindingsUrl), true);

            }
        }

        [TestMethod]
        public void ListAllServiceBindingsForUserProvidedServiceInstanceTest()
        {
            using (ShimsContext.Create())
            {
                MockClients clients = new MockClients();

                string json = @"{
  ""total_results"": 1,
  ""total_pages"": 1,
  ""prev_url"": null,
  ""next_url"": null,
  ""resources"": [
    {
      ""metadata"": {
        ""guid"": ""ffe97ab5-f2aa-4e9c-b07d-a9ae5a628b2b"",
        ""url"": ""/v2/service_bindings/ffe97ab5-f2aa-4e9c-b07d-a9ae5a628b2b"",
        ""created_at"": ""2016-02-05T12:14:40Z"",
        ""updated_at"": null
      },
      ""entity"": {
        ""app_guid"": ""39dd2c67-1404-481a-b0bb-6736fcda9282"",
        ""service_instance_guid"": ""897c4b74-1ad4-410a-a7bc-520249ef6196"",
        ""credentials"": {
          ""creds-key-166"": ""creds-val-166""
        },
        ""binding_options"": {

        },
        ""gateway_data"": null,
        ""gateway_name"": """",
        ""syslog_drain_url"": null,
        ""app_url"": ""/v2/apps/39dd2c67-1404-481a-b0bb-6736fcda9282"",
        ""service_instance_url"": ""/v2/user_provided_service_instances/897c4b74-1ad4-410a-a7bc-520249ef6196""
      }
    }
  ]
}";
                clients.JsonResponse = json;

                clients.ExpectedStatusCode = (HttpStatusCode)200;
                var cfClient = clients.CreateCloudFoundryClient();

                Guid? guid = Guid.NewGuid();


                var obj = cfClient.UserProvidedServiceInstances.ListAllServiceBindingsForUserProvidedServiceInstance(guid).Result;

                Assert.AreEqual("1", TestUtil.ToTestableString(obj.Properties.TotalResults), true);
                Assert.AreEqual("1", TestUtil.ToTestableString(obj.Properties.TotalPages), true);
                Assert.AreEqual("", TestUtil.ToTestableString(obj.Properties.PreviousUrl), true);
                Assert.AreEqual("", TestUtil.ToTestableString(obj.Properties.NextUrl), true);
                Assert.AreEqual("ffe97ab5-f2aa-4e9c-b07d-a9ae5a628b2b", TestUtil.ToTestableString(obj[0].EntityMetadata.Guid), true);
                Assert.AreEqual("/v2/service_bindings/ffe97ab5-f2aa-4e9c-b07d-a9ae5a628b2b", TestUtil.ToTestableString(obj[0].EntityMetadata.Url), true);
                Assert.AreEqual("2016-02-05T12:14:40Z", TestUtil.ToTestableString(obj[0].EntityMetadata.CreatedAt), true);
                Assert.AreEqual("", TestUtil.ToTestableString(obj[0].EntityMetadata.UpdatedAt), true);
                Assert.AreEqual("39dd2c67-1404-481a-b0bb-6736fcda9282", TestUtil.ToTestableString(obj[0].AppGuid), true);
                Assert.AreEqual("897c4b74-1ad4-410a-a7bc-520249ef6196", TestUtil.ToTestableString(obj[0].ServiceInstanceGuid), true);
                Assert.AreEqual("", TestUtil.ToTestableString(obj[0].GatewayData), true);
                Assert.AreEqual("", TestUtil.ToTestableString(obj[0].GatewayName), true);
                Assert.AreEqual("", TestUtil.ToTestableString(obj[0].SyslogDrainUrl), true);
                Assert.AreEqual("/v2/apps/39dd2c67-1404-481a-b0bb-6736fcda9282", TestUtil.ToTestableString(obj[0].AppUrl), true);
                Assert.AreEqual("/v2/user_provided_service_instances/897c4b74-1ad4-410a-a7bc-520249ef6196", TestUtil.ToTestableString(obj[0].ServiceInstanceUrl), true);

            }
        }

    }
}