//------------------------------------------------------------------------------
// <auto-generated>
  //     This code was generated by a tool.
  //
  //     Changes to this file may cause incorrect behavior and will be lost if
  //     the code is regenerated.
  // </auto-generated>
//------------------------------------------------------------------------------

//
// This source code was auto-generated by cf-sdk-builder
//

using CloudFoundry.CloudController.V2.Client.Data;
using Microsoft.QualityTools.Testing.Fakes;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using System;
using System.CodeDom.Compiler;
using System.Net;
using System.Threading.Tasks;

namespace CloudFoundry.CloudController.V2.Client.Test.Fake
{
    [TestClass]
    [GeneratedCodeAttribute("cf-sdk-builder", "1.0.0.0")]
    public class AppUsageEventsEndpoint
{
        [TestMethod]
        public void PurgeAndReseedAppUsageEventsTest()
        {
            using (ShimsContext.Create())
            {
                MockClients clients = new MockClients();

                clients.ExpectedStatusCode = (HttpStatusCode)204;
                var cfClient = clients.CreateCloudFoundryClient();


                cfClient.AppUsageEvents.PurgeAndReseedAppUsageEvents().Wait();

            }
        }

        [TestMethod]
        public void ListAllAppUsageEventsTest()
        {
            using (ShimsContext.Create())
            {
                MockClients clients = new MockClients();

                string json = @"{
  ""total_results"": 2,
  ""total_pages"": 2,
  ""prev_url"": null,
  ""next_url"": ""/v2/app_usage_events?after_guid=02c8e9b0-4ca6-4bf4-a1a2-73577e8756d0=asc=2=1"",
  ""resources"": [
    {
      ""metadata"": {
        ""guid"": ""964f6da1-f2fb-4019-95f8-a602b918e0f3"",
        ""url"": ""/v2/app_usage_events/964f6da1-f2fb-4019-95f8-a602b918e0f3"",
        ""created_at"": ""2016-02-05T12:14:47Z""
      },
      ""entity"": {
        ""state"": ""STARTED"",
        ""memory_in_mb_per_instance"": 564,
        ""instance_count"": 1,
        ""app_guid"": ""guid-79852c74-e495-4d07-8671-f5f7c69495e5"",
        ""app_name"": ""name-1643"",
        ""space_guid"": ""guid-be0e901b-af2f-4958-bccf-f738740fcfd7"",
        ""space_name"": ""name-1644"",
        ""org_guid"": ""guid-fc01d4e0-071d-46f9-9bf6-562a68e7fdd0"",
        ""buildpack_guid"": ""guid-d9911fde-bf80-40e6-95f2-bc675b161011"",
        ""buildpack_name"": ""name-1645"",
        ""package_state"": ""STAGED"",
        ""parent_app_guid"": null,
        ""parent_app_name"": null,
        ""process_type"": ""web""
      }
    }
  ]
}";
                clients.JsonResponse = json;

                clients.ExpectedStatusCode = (HttpStatusCode)200;
                var cfClient = clients.CreateCloudFoundryClient();


                var obj = cfClient.AppUsageEvents.ListAllAppUsageEvents().Result;

                Assert.AreEqual("2", TestUtil.ToTestableString(obj.Properties.TotalResults), true);
                Assert.AreEqual("2", TestUtil.ToTestableString(obj.Properties.TotalPages), true);
                Assert.AreEqual("", TestUtil.ToTestableString(obj.Properties.PreviousUrl), true);
                Assert.AreEqual("/v2/app_usage_events?after_guid=02c8e9b0-4ca6-4bf4-a1a2-73577e8756d0=asc=2=1", TestUtil.ToTestableString(obj.Properties.NextUrl), true);
                Assert.AreEqual("964f6da1-f2fb-4019-95f8-a602b918e0f3", TestUtil.ToTestableString(obj[0].EntityMetadata.Guid), true);
                Assert.AreEqual("/v2/app_usage_events/964f6da1-f2fb-4019-95f8-a602b918e0f3", TestUtil.ToTestableString(obj[0].EntityMetadata.Url), true);
                Assert.AreEqual("2016-02-05T12:14:47Z", TestUtil.ToTestableString(obj[0].EntityMetadata.CreatedAt), true);
                Assert.AreEqual("STARTED", TestUtil.ToTestableString(obj[0].State), true);
                Assert.AreEqual("564", TestUtil.ToTestableString(obj[0].MemoryInMbPerInstance), true);
                Assert.AreEqual("1", TestUtil.ToTestableString(obj[0].InstanceCount), true);
                Assert.AreEqual("guid-79852c74-e495-4d07-8671-f5f7c69495e5", TestUtil.ToTestableString(obj[0].AppGuid), true);
                Assert.AreEqual("name-1643", TestUtil.ToTestableString(obj[0].AppName), true);
                Assert.AreEqual("guid-be0e901b-af2f-4958-bccf-f738740fcfd7", TestUtil.ToTestableString(obj[0].SpaceGuid), true);
                Assert.AreEqual("name-1644", TestUtil.ToTestableString(obj[0].SpaceName), true);
                Assert.AreEqual("guid-fc01d4e0-071d-46f9-9bf6-562a68e7fdd0", TestUtil.ToTestableString(obj[0].OrgGuid), true);
                Assert.AreEqual("guid-d9911fde-bf80-40e6-95f2-bc675b161011", TestUtil.ToTestableString(obj[0].BuildpackGuid), true);
                Assert.AreEqual("name-1645", TestUtil.ToTestableString(obj[0].BuildpackName), true);
                Assert.AreEqual("STAGED", TestUtil.ToTestableString(obj[0].PackageState), true);
                Assert.AreEqual("", TestUtil.ToTestableString(obj[0].ParentAppGuid), true);
                Assert.AreEqual("", TestUtil.ToTestableString(obj[0].ParentAppName), true);
                Assert.AreEqual("web", TestUtil.ToTestableString(obj[0].ProcessType), true);

            }
        }

        [TestMethod]
        public void RetrieveAppUsageEventTest()
        {
            using (ShimsContext.Create())
            {
                MockClients clients = new MockClients();

                string json = @"{
  ""metadata"": {
    ""guid"": ""8acab8f8-bb8d-4677-a6e2-fbad9a05981f"",
    ""url"": ""/v2/app_usage_events/8acab8f8-bb8d-4677-a6e2-fbad9a05981f"",
    ""created_at"": ""2016-02-05T12:14:46Z""
  },
  ""entity"": {
    ""state"": ""STARTED"",
    ""memory_in_mb_per_instance"": 564,
    ""instance_count"": 1,
    ""app_guid"": ""guid-5e145e3a-f997-4c4f-8544-4fee94cf3420"",
    ""app_name"": ""name-1631"",
    ""space_guid"": ""guid-743189d5-c813-44fd-95f3-df25e69bf50f"",
    ""space_name"": ""name-1632"",
    ""org_guid"": ""guid-d6d4e987-035d-4284-ae3c-0d7bddc93670"",
    ""buildpack_guid"": ""guid-f09c8be6-544a-4d43-82eb-f754be940a2d"",
    ""buildpack_name"": ""name-1633"",
    ""package_state"": ""STAGED"",
    ""parent_app_guid"": null,
    ""parent_app_name"": null,
    ""process_type"": ""web""
  }
}";
                clients.JsonResponse = json;

                clients.ExpectedStatusCode = (HttpStatusCode)200;
                var cfClient = clients.CreateCloudFoundryClient();

                Guid? guid = Guid.NewGuid();


                var obj = cfClient.AppUsageEvents.RetrieveAppUsageEvent(guid).Result;


                Assert.AreEqual("8acab8f8-bb8d-4677-a6e2-fbad9a05981f", TestUtil.ToTestableString(obj.EntityMetadata.Guid), true);
                Assert.AreEqual("/v2/app_usage_events/8acab8f8-bb8d-4677-a6e2-fbad9a05981f", TestUtil.ToTestableString(obj.EntityMetadata.Url), true);
                Assert.AreEqual("2016-02-05T12:14:46Z", TestUtil.ToTestableString(obj.EntityMetadata.CreatedAt), true);
                Assert.AreEqual("STARTED", TestUtil.ToTestableString(obj.State), true);
                Assert.AreEqual("564", TestUtil.ToTestableString(obj.MemoryInMbPerInstance), true);
                Assert.AreEqual("1", TestUtil.ToTestableString(obj.InstanceCount), true);
                Assert.AreEqual("guid-5e145e3a-f997-4c4f-8544-4fee94cf3420", TestUtil.ToTestableString(obj.AppGuid), true);
                Assert.AreEqual("name-1631", TestUtil.ToTestableString(obj.AppName), true);
                Assert.AreEqual("guid-743189d5-c813-44fd-95f3-df25e69bf50f", TestUtil.ToTestableString(obj.SpaceGuid), true);
                Assert.AreEqual("name-1632", TestUtil.ToTestableString(obj.SpaceName), true);
                Assert.AreEqual("guid-d6d4e987-035d-4284-ae3c-0d7bddc93670", TestUtil.ToTestableString(obj.OrgGuid), true);
                Assert.AreEqual("guid-f09c8be6-544a-4d43-82eb-f754be940a2d", TestUtil.ToTestableString(obj.BuildpackGuid), true);
                Assert.AreEqual("name-1633", TestUtil.ToTestableString(obj.BuildpackName), true);
                Assert.AreEqual("STAGED", TestUtil.ToTestableString(obj.PackageState), true);
                Assert.AreEqual("", TestUtil.ToTestableString(obj.ParentAppGuid), true);
                Assert.AreEqual("", TestUtil.ToTestableString(obj.ParentAppName), true);
                Assert.AreEqual("web", TestUtil.ToTestableString(obj.ProcessType), true);

            }
        }

    }
}